// Copyright 2025 qc <2192629378@qq.com>. All Rights Reserved.
// Use of this source code is governed by a MIT style
// License that can be found in the LICENSE file.
// Code generated by "codegen -type=ErrorCode /Users/qc/dev-toolkit/internal/pkg/code"; DO NOT EDIT.

package code

// ErrorCodeString returns "HTTP: msg" for code.
func ErrorCodeString(code ErrorCode) string {
	switch code {
	case ErrUnknown:
		return "500: Internal server error"
	case ErrInvalidArg:
		return "400: Invalid argument"
	case ErrUnauthorized:
		return "401: Unauthorized"
	case ErrForbidden:
		return "403: Forbidden"
	case ErrNotFound:
		return "404: Not found"
	case ErrInternal:
		return "500: Internal server error"
	case ErrDeadlineExceeded:
		return "408: Deadline exceeded"
	default:
		return "500: unknown"
	}
}
