#!/usr/bin/env bash
# get bash from env, because some system may not install bash by default

# Copyright 2025 qc <2192629378@qq.com>. All Rights Reserved.
# Use of this source code is governed by a MIT style
# License that can be found in the LICENSE file.

# 当前项目源码根目录
PROJECT_ROOT=$(dirname "${BASH_SOURCE[0]}")/../..

# 读取项目配置（可选）
CONFIG_FILE="${PROJECT_ROOT}/configs/project.env"
if [ -f "${CONFIG_FILE}" ]; then
  set -a
  # shellcheck disable=SC1090
  . "${CONFIG_FILE}"
  set +a
fi

PROJECT_NAME=${PROJECT_NAME:-"dev-toolkit"}

# 生成文件存放目录
LOCAL_OUTPUT_ROOT="${PROJECT_ROOT}/${OUT_DIR:-_output}"

# 设置统一密码，方便记忆
# ''  严格字面量
# ""  允许变量展开
readonly PASSWORD=${PASSWORD:-'20030329'}

# Linux系统 going 用户
readonly LINUX_USERNAME=${LINUX_USERNAME:-going}
# Linux root & going 用户密码
readonly LINUX_PASSWORD=${LINUX_PASSWORD:-${PASSWORD}}

# 设置安装目录
readonly INSTALL_DIR=${INSTALL_DIR:-${HOME}/tmp/installation}
mkdir -p ${INSTALL_DIR}

# 环境变量路径
readonly ENV_FILE=${PROJECT_ROOT}/scripts/install/environment.sh

# 数据库配置信息

# MariaDB 配置信息
readonly MARIADB_ADMIN_USERNAME=${MARIADB_ADMIN_USERNAME:-root} # MariaDB root 用户
readonly MARIADB_ADMIN_PASSWORD=${MARIADB_ADMIN_PASSWORD:-${PASSWORD}} # MariaDB root 用户密码
readonly MARIADB_HOST=${MARIADB_HOST:-127.0.0.1:3306} # MariaDB 主机地址
readonly MARIADB_DATABASE=${MARIADB_DATABASE:-"${PROJECT_NAME}"} # MariaDB ${PROJECT_NAME} 应用使用的数据库名
readonly MARIADB_USERNAME=${MARIADB_USERNAME:-"${PROJECT_NAME}"} # ${PROJECT_NAME} 数据库用户名
readonly MARIADB_PASSWORD=${MARIADB_PASSWORD:-${PASSWORD}} # ${PROJECT_NAME} 数据库密码

# Redis 配置信息
readonly REDIS_HOST=${REDIS_HOST:-127.0.0.1} # Redis 主机地址
readonly REDIS_PORT=${REDIS_PORT:-6379} # Redis 监听端口
readonly REDIS_USERNAME=${REDIS_USERNAME:-''} # Redis 用户名
readonly REDIS_PASSWORD=${REDIS_PASSWORD:-${PASSWORD}} # Redis 密码

# MongoDB 配置
readonly MONGO_ADMIN_USERNAME=${MONGO_ADMIN_USERNAME:-root} # MongoDB root 用户
readonly MONGO_ADMIN_PASSWORD=${MONGO_ADMIN_PASSWORD:-${PASSWORD}} # MongoDB root 用户密码
readonly MONGO_HOST=${MONGO_HOST:-127.0.0.1} # MongoDB 地址
readonly MONGO_PORT=${MONGO_PORT:-27017} # MongoDB 端口
readonly MONGO_USERNAME=${MONGO_USERNAME:-"${PROJECT_NAME}"} # MongoDB 用户名
readonly MONGO_PASSWORD=${MONGO_PASSWORD:-${PASSWORD}} # MongoDB 密码

# 项目总配置
readonly PROJECT_DATA_DIR=${PROJECT_DATA_DIR:-${HOME}/data/${PROJECT_NAME}} # 项目 各组件数据目录
readonly PROJECT_INSTALL_DIR=${PROJECT_INSTALL_DIR:-${HOME}/opt/${PROJECT_NAME}} # 项目 各组件安装文件存放目录
readonly PROJECT_CONFIG_DIR=${PROJECT_CONFIG_DIR:-${HOME}/etc/${PROJECT_NAME}} # 项目 各组件配置文件存放目录
readonly PROJECT_LOG_DIR=${PROJECT_LOG_DIR:-${HOME}/var/log/${PROJECT_NAME}} # 项目 各组件日志文件存放目录
readonly CA_FILE=${CA_FILE:-${PROJECT_CONFIG_DIR}/cert/ca.pem} # 项目 CA 证书文件

# apiserver 配置
readonly APISERVER_HOST=${APISERVER_HOST:-127.0.0.1} # apiserver 部署机器 IP 地址
readonly APISERVER_GRPC_BIND_ADDRESS=${APISERVER_GRPC_BIND_ADDRESS:-0.0.0.0}
readonly APISERVER_GRPC_BIND_PORT=${APISERVER_GRPC_BIND_PORT:-8081}
readonly APISERVER_INSECURE_BIND_ADDRESS=${APISERVER_INSECURE_BIND_ADDRESS:-127.0.0.1}
readonly APISERVER_INSECURE_BIND_PORT=${APISERVER_INSECURE_BIND_PORT:-8080}
readonly APISERVER_SECURE_BIND_ADDRESS=${APISERVER_SECURE_BIND_ADDRESS:-0.0.0.0}
readonly APISERVER_SECURE_BIND_PORT=${APISERVER_SECURE_BIND_PORT:-8443}
readonly APISERVER_SECURE_TLS_CERT_KEY_CERT_FILE=${APISERVER_SECURE_TLS_CERT_KEY_CERT_FILE:-${PROJECT_CONFIG_DIR}/cert/apiserver.pem}
readonly APISERVER_SECURE_TLS_CERT_KEY_PRIVATE_KEY_FILE=${APISERVER_SECURE_TLS_CERT_KEY_PRIVATE_KEY_FILE:-${PROJECT_CONFIG_DIR}/cert/apiserver-key.pem}

# authz-server 配置
readonly AUTHZ_SERVER_HOST=${AUTHZ_SERVER_HOST:-127.0.0.1} # authz-server 部署机器 IP 地址
readonly AUTHZ_SERVER_INSECURE_BIND_ADDRESS=${AUTHZ_SERVER_INSECURE_BIND_ADDRESS:-127.0.0.1}
readonly AUTHZ_SERVER_INSECURE_BIND_PORT=${AUTHZ_SERVER_INSECURE_BIND_PORT:-9090}
readonly AUTHZ_SERVER_SECURE_BIND_ADDRESS=${AUTHZ_SERVER_SECURE_BIND_ADDRESS:-0.0.0.0}
readonly AUTHZ_SERVER_SECURE_BIND_PORT=${AUTHZ_SERVER_SECURE_BIND_PORT:-9443}
readonly AUTHZ_SERVER_SECURE_TLS_CERT_KEY_CERT_FILE=${AUTHZ_SERVER_SECURE_TLS_CERT_KEY_CERT_FILE:-${PROJECT_CONFIG_DIR}/cert/authz-server.pem}
readonly AUTHZ_SERVER_SECURE_TLS_CERT_KEY_PRIVATE_KEY_FILE=${AUTHZ_SERVER_SECURE_TLS_CERT_KEY_PRIVATE_KEY_FILE:-${PROJECT_CONFIG_DIR}/cert/authz-server-key.pem}
readonly AUTHZ_SERVER_CLIENT_CA_FILE=${AUTHZ_SERVER_CLIENT_CA_FILE:-${CA_FILE}}
readonly AUTHZ_SERVER_RPCSERVER=${AUTHZ_SERVER_RPCSERVER:-${APISERVER_HOST}:${APISERVER_GRPC_BIND_PORT}}

# pump 配置
readonly PUMP_HOST=${PUMP_HOST:-127.0.0.1} # pump 部署机器 IP 地址
readonly PUMP_COLLECTION_NAME=${PUMP_COLLECTION_NAME:-analytics}
readonly PUMP_MONGO_URL=${PUMP_MONGO_URL:-mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${PUMP_COLLECTION_NAME}?authSource=${PUMP_COLLECTION_NAME}}

# watcher 配置
readonly WATCHER_HOST=${WATCHER_HOST:-127.0.0.1} # watcher 部署机器 IP 地址

# ctl 配置
readonly CONFIG_USER_USERNAME=${CONFIG_USER_USERNAME:-admin}
readonly CONFIG_USER_PASSWORD=${CONFIG_USER_PASSWORD:-Admin@2025}
readonly CONFIG_USER_CLIENT_CERTIFICATE=${CONFIG_USER_CLIENT_CERTIFICATE:-${HOME}/.${PROJECT_NAME}/cert/admin.pem}
readonly CONFIG_USER_CLIENT_KEY=${CONFIG_USER_CLIENT_KEY:-${HOME}/.${PROJECT_NAME}/cert/admin-key.pem}
readonly CONFIG_SERVER_ADDRESS=${CONFIG_SERVER_ADDRESS:-${APISERVER_HOST}:${APISERVER_SECURE_BIND_PORT}}
readonly CONFIG_SERVER_CERTIFICATE_AUTHORITY=${CONFIG_SERVER_CERTIFICATE_AUTHORITY:-${CA_FILE}}