// Copyright 2026 qc (GitHub: Ixecd). All rights reserved.
// Use of this source code is governed by an MIT-style license.

// Package sizing 提供资源优化 sizing 能力.
// Level5 扩展: VPA 协调预研 (只读模式，生成建议供用户手动应用).

package sizing

import (
	"fmt"
	"os"
	"strings"
)

// VPASuggestion 生成 VerticalPodAutoscaler 建议 YAML (只读模式)
//
// 用途:
//   - 输出可直接保存为 vpa-suggestion.yaml
//   - 用户可手动 `kubectl apply -f vpa-suggestion.yaml` 或忽略
//   - 保持 GitOps 原则: 建议可审计 + 人类最终确认
//
// 参数:
//   - namespace, name: 目标 Deployment 的命名空间 + 名称
//   - sug: sizing.Suggestion (包含推荐值 + 置信度)
//   - mode: VPA 更新模式 ("Off"=只推荐, "Initial"=启动时应用, "Auto"=自动调整)
//     默认 "Off" (只读模式，安全优先)
//
// 返回:
//   - string: VPA YAML 字符串，可直接写入文件
//   - error: 仅当参数非法时返回
//
// 设计原则:
//   - 只读优先: 默认 mode="Off"，不自动修改集群状态
//   - 可解释性: YAML 注释包含 sizing 决策依据 (profile/confidence)
//   - 零依赖: 纯字符串拼接，不引入 k8s.io/api 等重型依赖
func VPASuggestion(namespace, name string, sug *Suggestion, mode string) (string, error) {
	if namespace == "" || name == "" || sug == nil {
		return "", fmt.Errorf("invalid parameters: namespace=%q, name=%q, sug=%v", namespace, name, sug)
	}

	// 默认模式: Off (只读，安全优先)
	if mode == "" {
		mode = "Off"
	}
	// 校验模式
	validModes := map[string]bool{"Off": true, "Initial": true, "Auto": true}
	if !validModes[mode] {
		return "", fmt.Errorf("invalid VPA mode %q, expected one of: Off/Initial/Auto", mode)
	}

	// 计算 limits (简化: 2x requests，实际可按 Profile 调整)
	limitsCPU := sug.RecommendedCPU * 2
	limitsMem := sug.RecommendedMem * 2

	// 生成 YAML (注意: 缩进对齐 + 注释可解释性)
	// 使用 strings.Builder 避免多次拼接开销
	var b strings.Builder
	b.WriteString(fmt.Sprintf(`# vpa-suggestion: %s/%s
# Generated by KubePivot v2.9 sizing engine
# sizing profile: %s, confidence: %.2f
# savings: CPU %.1f%%, Mem %.1f%%
# VPA mode: %s (Off=只推荐, Initial=启动时应用, Auto=自动调整)
# ⚠️ 应用前请确认: kubectl apply --dry-run=client -f this-file.yaml
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: %s-vpa
  namespace: %s
  labels:
    app.kubernetes.io/managed-by: kubepivot
    kubepivot.io/sizing-version: "2.9"
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: %s
  updatePolicy:
    updateMode: "%s"
  resourcePolicy:
    containerPolicies:
    - containerName: main
      minAllowed:
        cpu: "%dm"
        memory: "%dMi"
      maxAllowed:
        cpu: "%dm"
        memory: "%dMi"
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits
`,
		name, namespace,
		sug.Profile, sug.Confidence,
		sug.SavingsCPU, sug.SavingsMem,
		mode,
		name, namespace,
		name,
		mode,
		sug.RecommendedCPU, sug.RecommendedMem>>20,
		limitsCPU, limitsMem>>20,
	))

	return b.String(), nil
}

// WriteVPASuggestion 辅助函数: 将 VPA 建议写入文件 (原子写入)
// 用途: 调用方可直接传入输出路径，避免重复写文件逻辑
func WriteVPASuggestion(path, namespace, name string, sug *Suggestion, mode string) error {
	content, err := VPASuggestion(namespace, name, sug, mode)
	if err != nil {
		return err
	}
	// 原子写入: 临时文件 + rename
	tmpPath := path + ".tmp"
	// 🔧 修复: 使用 content 变量
	if err := os.WriteFile(tmpPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("write temp file: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("atomic rename: %w", err)
	}
	return nil
}