// Copyright 2025 qc <2192629378@qq.com>. All Rights Reserved.
// Use of this source code is governed by a MIT style
// License that can be found in the LICENSE file.
// Code generated by "codegen -type=ErrorCode ."; DO NOT EDIT.

package code

// ErrorCodeString returns "HTTP: msg" for code.
func ErrorCodeString(code ErrorCode) string {
	switch code {
	case ErrUnknown:
		return "500: Internal server error"
	case ErrInvalidArg:
		return "400: Invalid argument"
	case ErrUnauthorized:
		return "401: Unauthorized"
	case ErrForbidden:
		return "403: Forbidden"
	case ErrNotFound:
		return "404: Not found"
	case ErrInternal:
		return "500: Internal server error"
	case ErrDeadlineExceeded:
		return "408: Deadline exceeded"
	case ErrRouteProviderNotAvailable:
		return "503: Route provider is not available in current cluster"
	case ErrRouteResourceNotFound:
		return "404: Traffic resource (Ingress or HTTPRoute) not found"
	case ErrRouteInvalid:
		return "400: Route rule is invalid"
	case ErrRouteApplyFailed:
		return "500: Apply route rules failed"
	case ErrRouteAutoDetectFailed:
		return "500: Auto detect route provider failed"
	default:
		return "500: unknown"
	}
}
