// Copyright 2025 qc <2192629378@qq.com>. All Rights Reserved.
// Use of this source code is governed by a MIT style
// License that can be found in the LICENSE file.
package main

import (
	"go/ast" // 语法数的各种类型和结构
	"go/constant"
	"go/format"
	"go/token"
	"go/types"

	"bytes"
	"flag"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"html/template"

	"golang.org/x/tools/go/packages"
)

var errCodeDocPrefix = `# 错误码

!!系统错误码列表，由 {{.}}codegen -type=int -doc{{.}} 命令生成，不要对此文件做任何更改。

## 功能说明

如果返回结果中存在 {{.}}code{{.}} 字段，则表示调用 API 接口失败。例如:

{{.}}{{.}}{{.}}json
{
  "code": 100101,
  "message": "Database error"
}
{{.}}{{.}}{{.}}

上述返回中 {{.}}code{{.}} 表示错误码, {{.}}message{{.}} 表示该错误的具体信息。每个错误同时也对应一个 HTTP 状态码，比如上述错误码对应了 HTTP 状态码 500(Internal Server Error)。

## 错误码列表

系统支持的错误码列表如下:

| Identifier | Code | HTTP Code | Description |
| ---------- | ---- | --------- | ----------- |
`

var (
	typeNames  = flag.String("type", "", "comma-separated list of type names; must be set")
	output     = flag.String("output", "", "output file name; default srcdir/<type>_string.go")
	trimprefix = flag.String("trimprefix", "", "trim the `prefix` from the generated constant names")
	// 条件编译，只允许在目录模式下使用
	buildTags = flag.String("tags", "", "comma-separated list of build tags to apply")
	// false 生成代码
	// true 生成文档
	doc = flag.Bool("doc", false, "if true, only generate error code documentation in markdown format")
)

// flags包的替代使用函数
func Usage() {
	// os.Stderr 不干扰正常输出流，符合Unix传统
	// os.Stdout 供管道、重定向使用
	fmt.Fprintf(os.Stderr, "Usage of codegen:\n")
	fmt.Fprintf(os.Stderr, "\tcodegen [flags] -type T [dir]\n")
	fmt.Fprintf(os.Stderr, "\tcodegen [flags] -type T files...# Must be a single package\n")
	fmt.Fprintf(os.Stderr, "Flags:\n")
	flag.PrintDefaults()
}

func main() {
	// 清除所有flags
	log.SetFlags(0)
	// 给所有日志添加 codegen: 前缀
	log.SetPrefix("codegen: ")
	// 把flag包默认的帮助函数替换成我们自定义的Usage函数
	flag.Usage = Usage
	// 解析命令行参数，并把参数值赋值给之前定义的变量
	flag.Parse()
	if len(*typeNames) == 0 {
		flag.Usage()
		os.Exit(2)
	}

	types := strings.Split(*typeNames, ",")
	var tags []string
	if len(*buildTags) > 0 {
		tags = strings.Split(*buildTags, ",")
	}
	// 可以接受目录或一组文件
	args := flag.Args()
	if len(args) == 0 {
		// 默认处理当前目录中的整个包
		args = []string{"."}
	}
	// 只解析包一次
	// dir用来保存目标包的目录路径
	var dir string
	g := Generator{
		// 工具会自动从所有提取的常量名中 去除这个前缀
		// 比如一个文件中有很多 ErrorCode 类型的变量
		// ErrUserNotFounc
		// ErrUserAlreadyExists
		// ErrUserInvalidToken ...
		// -trimprefix=ErrUser 就可以把前面的ErrUser去掉
		trimPrefix: *trimprefix,
	}

	if len(args) == 1 && isDirectory(args[0]) {
		dir = args[0]
	} else {
		// build tags 只能写在文件顶部，用户明确指定文件列表时，工具无法安全地在每个文件上添加tag
		if len(tags) != 0 {
			log.Fatal("-tags option applies only to dir, not when files are specified")
		}
		dir = filepath.Dir(args[0])
	}
	// 要么是目录模式 允许 -tags
	// 要么是文件模式 不允许 -tags
	// 加载 Go 包
	g.parsePackage(args, tags)

	if !*doc {
		// 打印头部和包语句
		g.Printf("Copyright 2025 qc <2192629378@qq.com>. All Rights Reserved.\n")
		g.Printf("Use of this source code is governed by a MIT style\n")
		g.Printf("License that can be found in the LICENSE file.")
		g.Printf("\n")
		g.Printf("// Code generated by \"codegen %s\"; DO NOT EDIT. \n", strings.Join(os.Args[1:], " "))
		g.Printf("\n")
		g.Printf("package %s", g.pkg.name)
		g.Printf("\n")
	}

	var src []byte
	for _, typeName := range types {
		if *doc {
			g.generateDocs(typeName)
			src = g.buf.Bytes()
		} else {
			g.generate(typeName)
			src = g.format()
		}
	}

	// Write to file.
	outputName := *output
	if outputName == "" {
		absDir, _ := filepath.Abs(dir)
		baseName := fmt.Sprintf("%s_generated.go", strings.ReplaceAll(filepath.Base(absDir), "-", "_"))
		if len(flag.Args()) == 1 {
			baseName = fmt.Sprintf(
				"%s_generated.go",
				strings.ReplaceAll(filepath.Base(strings.TrimSuffix(flag.Args()[0], ".go")), "-", "_"),
			)
		}

		outputName = filepath.Join(dir, strings.ToLower(baseName))
	}
	err := ioutil.WriteFile(outputName, src, 0o600)
	if err != nil {
		log.Fatalf("writing output: %s", err)
	}
}

type File struct {
	pkg  *Package
	file *ast.File

	typeName string
	values   []Value

	trimPrefix string
}

// Generator 保存分析的结果，主要是formt.Source的输出
type Generator struct {
	buf bytes.Buffer
	pkg *Package

	trimPrefix string
}

func (g *Generator) Printf(format string, args ...interface{}) {
	fmt.Fprintf(&g.buf, format, args...)
}

// parsePackage 分析从模式和标签构建的单个包。
// 如果出现错误，parsePackage 会退出。
func (g *Generator) parsePackage(patterns []string, tags []string) {
	cfg := &packages.Config{
		Mode: packages.LoadSyntax, // 需要 AST 树，遍历用的

		Tests:      false,
		BuildFlags: []string{fmt.Sprintf("-tags=%s", strings.Join(tags, " "))},
	}
	pkgs, err := packages.Load(cfg, patterns...)
	if err != nil {
		log.Fatal(err)
	}

	// 严格要求只加载一个包
	if len(pkgs) != 1 {
		log.Fatalf("error: %d packages found", len(pkgs))
	}
	g.addPackage(pkgs[0])
}

func (g *Generator) addPackage(pkg *packages.Package) {
	g.pkg = &Package{
		name:  pkg.Name,
		defs:  pkg.TypesInfo.Defs, // 关键: 标识符 -> types.Object 映射
		files: make([]*File, len(pkg.Syntax)),
	}

	// 把每个 AST 文件包装成 File 结构体
	for i, file := range pkg.Syntax {
		g.pkg.files[i] = &File{
			file:       file,
			pkg:        g.pkg,
			trimPrefix: g.trimPrefix,
		}
	}
}

func (g *Generator) generate(typeName string) {
	values := make([]Value, 0, 100)
	for _, file := range g.pkg.files {
		file.typeName = typeName
		file.values = nil
		if file.file != nil {
			ast.Inspect(file.file, file.genDecl)
			values = append(values, file.values...)
		}
	}
	if len(values) == 0 {
		log.Fatalf("no values defined for type %s", typeName)
	}

	g.Printf("\t// init register errro codes defines in this source code to *****\n")
	g.Printf("func init() {\n")
	for _, v := range values {
		code, description := v.ParseComment()
		g.Printf("\tregister(%s, %s, \"%s\")\n", v.originalName, code, description)
	}
	g.Printf("}\n")
}

func (g *Generator) generateDocs(typeName string) {
	values := make([]Value, 0, 100)
	for _, file := range g.pkg.files {
		// file.genDecl 是 File 的方法，它需要知道找哪个类型的常量
		// genDecl 里会用 f.typeName 来判断您当前常量块是否使我们关心的类型
		file.typeName = typeName
		// 每次处理新文件前，需要把这个文件上一次(如果有)收到的常量清空
		file.values = nil
		if file.file != nil {
			// 深度优先遍历工具,会递归访问 AST 的每一个节点
			// 第二个参数是一个函数, func(node ast.Node) bool
			// 	如果返回 true -> 继续遍历子节点
			// 	如果返回 false -> 停止遍历当前分支
			ast.Inspect(file.file, file.genDecl)
			values = append(values, file.values...)
		}
	}

	// 防御性编程: 宁可让工具失败，也不要生成空文件误导用户
	if len(values) == 0 {
		log.Fatalf("no values defined for type %s", typeName)
	}

	// 生成 Markdown文件, {{.}}是占位符，替换为 `
	tmpl, _ := template.New("doc").Parse(errCodeDocPrefix)
	var buf bytes.Buffer
	_ = tmpl.Execute(&buf, "`")

	g.Printf(buf.String())
	for _, v := range values {
		code, description := v.ParseComment()
		g.Printf("| %s | %d | %s | %s |\n", v.originalName, v.value, code, description)
	}
	g.Printf("\n")
}

func (g *Generator) format() []byte {
	src, err := format.Source(g.buf.Bytes())
	if err != nil {
		log.Printf("warning: internal error: invalid Go generated: %s", err)
		log.Printf("warning: compile the package to analyze the error")

		return g.buf.Bytes()
	}
	return src
}

type Package struct {
	name  string
	defs  map[*ast.Ident]types.Object
	files []*File
}

func isDirectory(name string) bool {
	info, err := os.Stat(name)
	if err != nil {
		log.Fatal(err)
	}
	return info.IsDir()
}

type Value struct {
	comment      string
	originalName string
	name         string

	value  uint64
	signed bool
	str    string
}

func (v *Value) String() string {
	return v.str
}

// genDecl 常量提取函数
// 这是一个 ast.Inspect 的回调函数
func (f *File) genDecl(node ast.Node) bool {
	// 判断当前节点是否是通用声明, 并且其token是否为 CONST
	decl, ok := node.(*ast.GenDecl)
	// 只处理常量声明
	if !ok || decl.Tok != token.CONST {
		return true
	}
	// 确定常量块的类型(支持 iota 和显示类型)
	// 通过第一项推断或显示类型获取
	typ := ""

	for _, spec := range decl.Specs {
		vspec, _ := spec.(*ast.ValueSpec)
		// 情况1: iota 隐式类型
		if vspec.Type == nil && len(vspec.Values) > 0 {
			typ = ""

			ce, ok := vspec.Values[0].(*ast.CallExpr)
			if !ok {
				continue
			}
			id, ok := ce.Fun.(*ast.Ident)
			if !ok {
				continue
			}
			typ = id.Name
		}
		// 情况2: 显式类型
		if vspec.Type != nil {
			ident, ok := vspec.Type.(*ast.Ident)
			if !ok {
				continue
			}
			typ = ident.Name
		}
		// 当前 const 块不是我们要的类型
		if typ != f.typeName {
			continue
		}
		// 提取所有匹配 typeName 的常量名
		for _, name := range vspec.Names {
			// 跳过空白标识符
			if name.Name == "_" {
				continue
			}
			// 通过映射拿到 types.Object
			// map[*ast.Ident]types.Object，其来自 packages.Load 的 TypesInfo.Defs
			// 拿到 真实的类型检查后的对象， 从而获取常量真实值
			obj, ok := f.pkg.defs[name]
			if !ok {
				log.Fatalf("no values for constant %s", name)
			}
			// 验证是整数类型,int uint int64都行,不支持 string float等
			info := obj.Type().Underlying().(*types.Basic).Info()
			if info&types.IsInteger == 0 {
				log.Fatalf("can't handle non-integer constant type %s", typ)
			}
			// 提取常量真实值(支持有符号和无符号)
			value := obj.(*types.Const).Val() // Guaranteed to succeed as this is CONST.
			if value.Kind() != constant.Int {
				log.Fatalf("can't happen: constant is not an integer %s", name)
			}
			i64, isInt := constant.Int64Val(value)
			u64, isUint := constant.Uint64Val(value)
			if !isInt && !isUint {
				log.Fatalf("internal error: value of %s is not an integer: %s", name, value.String())
			}
			if !isInt {
				// 有符号转无符号统一存储
				u64 = uint64(i64)
			}
			v := Value{
				originalName: name.Name,
				value:        u64,
				signed:       info&types.IsUnsigned == 0,
				str:          value.String(),
			}
			if vspec.Doc != nil && vspec.Doc.Text() != "" {
				// const 块上面的文档注释
				v.comment = vspec.Doc.Text()
			} else if c := vspec.Comment; c != nil && len(c.List) == 1 {
				// 常量名后面的 // 注释
				v.comment = c.Text()
			}

			v.name = strings.TrimPrefix(v.originalName, f.trimPrefix)
			f.values = append(f.values, v)
		}
	}
	// 一旦处理完一个匹配的const块,返回false停止遍历其子节点
	return false
}

func (v *Value) ParseComment() (string, string) {
	reg := regexp.MustCompile(`\w\s*-\s*(\d{3})\s*:\s*([A-Z].*)\s*\.\n*`)
	if !reg.MatchString(v.comment) {
		log.Printf("constant '%s' have wrong comment format, register with 500 as default", v.originalName)

		return "500", "Internal server error"
	}

	groups := reg.FindStringSubmatch(v.comment)
	if len(groups) != 3 {
		return "500", "Internal server error"
	}

	return groups[1], groups[2]
}