package scaffold

import (
	"errors"
	"fmt"
	"io"
	"io/fs"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"unicode/utf8"
)

type InitOptions struct {
	Name         string
	Module       string
	OutputDir    string
	TemplateRoot string
	Force        bool
	WithFrontend bool
	Stdout       io.Writer
}

var (
	projectNamePattern = regexp.MustCompile(`^[a-z0-9-]+$`)
	copyEntries        = []string{
		".editorconfig",
		".gitignore",
		".gitlint",
		".golangci.yaml",
		".vscode",
		"build",
		"configs",
		"deployments",
		"docs",
		"githooks",
		"scripts",
		"templates",
		"tools",
		"docker-compose.yml",
		"LICENSE",
		"Makefile",
		"README.md",
	}
)

func InitProject(opts InitOptions) (err error) {
	name := strings.TrimSpace(opts.Name)
	if name == "" {
		return errors.New("missing project name: use --name")
	}
	if !projectNamePattern.MatchString(name) {
		return fmt.Errorf("invalid project name %q: use lowercase letters, numbers, and '-' only", name)
	}
	module := strings.TrimSpace(opts.Module)
	if module == "" {
		module = name
	}
	if opts.Stdout == nil {
		opts.Stdout = io.Discard
	}

	templateRoot, err := resolveTemplateRoot(opts.TemplateRoot)
	if err != nil {
		return err
	}

	outputDir, err := resolveOutputDir(opts.OutputDir, name)
	if err != nil {
		return err
	}

	// 记录目录是否由本次 init 创建
	// --force 时目录已存在，失败不能删（里面可能有用户文件）
	_, statErr := os.Stat(outputDir)
	createdByUs := os.IsNotExist(statErr) && !opts.Force

	if err = ensureOutputDir(outputDir, opts.Force, name); err != nil {
		return err
	}

	// 初始化失败时自动清理半成品目录
	defer func() {
		if err != nil && createdByUs {
			slog.Debug("初始化失败，清理半成品目录", "dir", outputDir)
			if removeErr := os.RemoveAll(outputDir); removeErr != nil {
				slog.Debug("清理失败", "dir", outputDir, "err", removeErr)
				return
			}
			fmt.Fprintf(opts.Stdout, "⚠️  初始化失败，已自动清理：%s\n", friendlyPath(outputDir))
		}
	}()

	for _, entry := range copyEntries {
		src := filepath.Join(templateRoot, entry)
		dst := filepath.Join(outputDir, entry)
		if err := copyPath(src, dst); err != nil {
			return fmt.Errorf("copy %s: %w", entry, err)
		}
	}

	if err := writeGoMod(filepath.Join(templateRoot, "go.mod"), filepath.Join(outputDir, "go.mod"), module); err != nil {
		return err
	}
	if err := writeServiceMain(filepath.Join(outputDir, "cmd", name, "main.go"), name); err != nil {
		return err
	}
	if err := writeComponentsConfig(filepath.Join(outputDir, "configs", "components.yaml"), name); err != nil {
		return err
	}
	if err := writeTestScript(filepath.Join(outputDir, "scripts", "test_api.sh"), name); err != nil {
		return err
	}
	if err := writeInternalSkeleton(outputDir, name, module); err != nil {
		return err
	}
	if err := writeMigrationSkeleton(outputDir, name); err != nil {
		return err
	}
	if err := writeAuthPackage(outputDir); err != nil {
		return err
	}
	if err := writeMetricsSkeleton(outputDir, name); err != nil {
		return err
	}
	if err := writeMonitoringSkeleton(outputDir, name); err != nil {
		return err
	}
	if err := writeTestSkeleton(outputDir, name, module); err != nil {
		return err
	}
	if err := writeSnapshotSkeleton(outputDir, name); err != nil {
		return err
	}
	if err := writeSwaggerSpec(outputDir, name); err != nil {
		return err
	}

	// 🔥 FIXED: gen project.env for deploy (raw string)
	configsPath := filepath.Join(outputDir, "configs", "project.env")
	envContent := fmt.Sprintf(`# Auto-generated by dtk init for deploy
PROJECT_NAME=%s
KUBE_NAMESPACE=%s
KUBE_CONTEXT=
KUBE_CONFIG=
MODULE_PATH=%s
REGISTRY_PREFIX=qingchun22
`, name, name, module)
	if err := os.WriteFile(configsPath, []byte(envContent), 0644); err != nil {
		return fmt.Errorf("gen project.env: %w", err)
	}

	if err := renameDir(filepath.Join(outputDir, "build", "docker", "helloworld"), filepath.Join(outputDir, "build", "docker", name)); err != nil {
		return err
	}
	if err := renameDir(filepath.Join(outputDir, "build", "docker", "dtk"), filepath.Join(outputDir, "build", "docker", name)); err != nil {
		// ignore if not exist
	}
	if err := renameDir(filepath.Join(outputDir, "deployments", "project"), filepath.Join(outputDir, "deployments", name)); err != nil {
		return err
	}

	if err := writeDockerfile(filepath.Join(outputDir, "build", "docker", name, "Dockerfile"), name); err != nil {
		return err
	}
	if err := writeBuildSh(filepath.Join(outputDir, "build", "docker", name, "build.sh"), name); err != nil {
		return err
	}

	replacements := map[string]string{
		"github.com/Ixecd/dev-toolkit": module,
		"dev-toolkit":                  name,
	}

	if err := replaceInDir(outputDir, replacements); err != nil {
		return fmt.Errorf("content replacement failed: %w", err)
	}

	if err := replaceInDir(filepath.Join(outputDir, "deployments"), map[string]string{
		"project": name,
	}); err != nil {
		return fmt.Errorf("fix helm chart templates: %w", err)
	}

	// after replaceInDir
	fixChartYAMLs(outputDir, name)

	if err := writeHelmTemplateSkeleton(outputDir, name); err != nil {
		return err
	}

	// 🔥 ADD dir renames漏
	if err := renameDir(filepath.Join(outputDir, "deployments", "dev-toolkit"), filepath.Join(outputDir, "deployments", name)); err != nil {
		// ignore if not exist
	}
	if err := renameDir(filepath.Join(outputDir, "build", "docker", "dev-toolkit"), filepath.Join(outputDir, "build", "docker", name)); err != nil {
	}

	// 自动安装依赖
	if err := runInDir(outputDir, "git", "init"); err != nil {
		fmt.Fprintf(opts.Stdout, "[WARN] git init 失败，请手动执行\n")
	}
	if err := runInDir(outputDir, "git", "add", "."); err != nil {
		fmt.Fprintf(opts.Stdout, "[WARN] git add 失败，请手动执行\n")
	}
	if err := runInDir(outputDir, "git", "commit", "-m", "chore: init project by dtk"); err != nil {
		fmt.Fprintf(opts.Stdout, "[WARN] git commit 失败，请手动执行\n")
	}
	if err := runInDir(outputDir, "go", "get", "github.com/stretchr/testify@latest"); err != nil {
		fmt.Fprintf(opts.Stdout, "[WARN] go get testify 失败，请手动执行: go get github.com/stretchr/testify\n")
	}
	if err := runInDir(outputDir, "go", "get", "github.com/golang-jwt/jwt/v5"); err != nil {
		fmt.Fprintf(opts.Stdout, "[WARN] go get jwt 失败，请手动执行\n")
	}
	if err := runInDir(outputDir, "go", "get", "golang.org/x/crypto/bcrypt"); err != nil {
		fmt.Fprintf(opts.Stdout, "[WARN] go get bcrypt 失败，请手动执行\n")
	}
	if err := runInDir(outputDir, "go", "get", "github.com/prometheus/client_golang/prometheus"); err != nil {
		fmt.Fprintf(opts.Stdout, "[WARN] go get prometheus 失败，请手动执行\n")
	}
	if err := runInDir(outputDir, "go", "mod", "tidy"); err != nil {
		fmt.Fprintf(opts.Stdout, "[WARN] go mod tidy 失败，请手动执行\n")
	}

	// 友好路径显示（~/myproject 而不是绝对路径）
	friendly := friendlyPath(outputDir)

	fmt.Fprintf(opts.Stdout, "✅ 项目已成功生成！\n\n")
	fmt.Fprintf(opts.Stdout, "  路径    %s\n", friendly)
	fmt.Fprintf(opts.Stdout, "  模块    %s\n", module)
	fmt.Fprintf(opts.Stdout, "  入口    cmd/%s\n\n", name)
	fmt.Fprintf(opts.Stdout, "下一步：\n")
	fmt.Fprintf(opts.Stdout, "  cd %s\n", friendly)
	fmt.Fprintf(opts.Stdout, "  make tools   # 安装所有工具\n")
	fmt.Fprintf(opts.Stdout, "  make build   # 编译\n")
	fmt.Fprintf(opts.Stdout, "  make test    # 测试\n")

	if opts.WithFrontend {
		if err := writeFrontendSkeleton(outputDir, name); err != nil {
			return fmt.Errorf("gen frontend: %w", err)
		}
		fmt.Fprintf(opts.Stdout, "  cd %s/frontend && npm install && npm run dev  # 前端\n", friendly)
	}
	return nil
}

func runInDir(dir string, name string, args ...string) error {
	slog.Debug("执行命令", "cmd", name, "args", args, "dir", dir)
	cmd := exec.Command(name, args...)
	cmd.Dir = dir
	cmd.Stdout = io.Discard
	var errBuf strings.Builder
	cmd.Stderr = &errBuf
	err := cmd.Run()
	if err != nil {
		slog.Debug("命令执行失败",
			"cmd", name,
			"args", args,
			"stderr", strings.TrimSpace(errBuf.String()),
			"err", err,
		)
	}
	return err
}

func fixChartYAMLs(root, name string) {
	path := filepath.Join(root, "deployments", name, "Chart.yaml")
	data, err := os.ReadFile(path)
	if err != nil {
		return
	}
	// 清理 dependencies
	updated := regexp.MustCompile(`(?s)dependencies:.*?(?=maintainers:|annotations:|type:|\z)`).
		ReplaceAllString(string(data), "dependencies: []\n")
	os.WriteFile(path, []byte(updated), 0644)
}

func resolveTemplateRoot(explicit string) (string, error) {
	if explicit != "" {
		return filepath.Abs(explicit)
	}
	if env := strings.TrimSpace(os.Getenv("DTK_TEMPLATE_ROOT")); env != "" {
		return filepath.Abs(env)
	}

	cwd, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("get cwd: %w", err)
	}
	if isTemplateRoot(cwd) {
		return cwd, nil
	}
	return "", errors.New("template root not found: use --template or set DTK_TEMPLATE_ROOT")
}

func isTemplateRoot(path string) bool {
	required := []string{
		"Makefile",
		filepath.Join("scripts", "make-rules", "common.mk"),
		filepath.Join("githooks", "pre-commit.sh"),
	}
	for _, item := range required {
		if _, err := os.Stat(filepath.Join(path, item)); err != nil {
			return false
		}
	}
	return true
}

func resolveOutputDir(explicit, name string) (string, error) {
	if explicit == "" {
		explicit = name
	}
	return filepath.Abs(explicit)
}

func ensureOutputDir(path string, force bool, name string) error {
	info, err := os.Stat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return os.MkdirAll(path, 0o755)
		}
		return err
	}
	if !info.IsDir() {
		return fmt.Errorf("输出路径存在但不是目录：%s", friendlyPath(path))
	}

	// === 新增严格检查：目录已存在时默认直接失败（保护用户项目）===
	entries, err := os.ReadDir(path)
	if err != nil {
		return err
	}
	if len(entries) > 0 || !force {
		// 即使是空目录，也建议用户加 --force（更明确）
		if force {
			// force=true 时允许继续（会覆盖）
			return nil
		}
		return fmt.Errorf("输出目录已存在：%s\n\n"+
			"   请使用其他路径，或加 --force 强制覆盖：\n"+
			"     dtk init --name %s --output %s --force",
			friendlyPath(path), name, friendlyPath(path)) // 这里 name 是 InitProject 里的局部变量
	}
	return nil
}

func copyPath(src, dst string) error {
	info, err := os.Stat(src)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	if shouldSkip(filepath.Base(src)) {
		return nil
	}
	if info.IsDir() {
		return copyDir(src, dst)
	}
	return copyFile(src, dst)
}

func copyDir(src, dst string) error {
	return filepath.WalkDir(src, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		base := filepath.Base(path)
		if shouldSkip(base) {
			if d.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		if d.Type()&os.ModeSymlink != 0 {
			return nil
		}
		rel, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}
		target := filepath.Join(dst, rel)
		if d.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		return copyFile(path, target)
	})
}

func copyFile(src, dst string) error {
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return err
	}
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()

	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()

	if _, err := io.Copy(out, in); err != nil {
		return err
	}
	return out.Close()
}

func renameDir(oldPath, newPath string) error {
	// 源目录不存在就跳过（模板里可能没有）
	if _, err := os.Stat(oldPath); err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}

	// === 目标已存在时自动清理（--force 模式下安全）===
	if _, err := os.Stat(newPath); err == nil {
		if err := os.RemoveAll(newPath); err != nil {
			return fmt.Errorf("清理旧目录失败 %s: %w", newPath, err)
		}
	}

	if err := os.MkdirAll(filepath.Dir(newPath), 0o755); err != nil {
		return err
	}
	return os.Rename(oldPath, newPath)
}

func isText(data []byte) bool {
	if !utf8.Valid(data) {
		return false
	}
	return !bytesContainsZero(data)
}

func bytesContainsZero(data []byte) bool {
	for _, b := range data {
		if b == 0 {
			return true
		}
	}
	return false
}

func shouldSkip(name string) bool {
	switch name {
	case ".git", ".cursor", "_output", "node_modules", ".DS_Store":
		return true
	default:
		return false
	}
}

func replaceInDir(root string, replacements map[string]string) error {
	// 目录不存在时优雅跳过
	// 常见于模板中没有 deployments/project 子目录的情况
	if _, err := os.Stat(root); err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}

	return filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		if d.Type()&os.ModeSymlink != 0 {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if !isText(data) {
			return nil
		}
		updated := string(data)
		for oldValue, newValue := range replacements {
			updated = strings.ReplaceAll(updated, oldValue, newValue)
		}
		if updated == string(data) {
			return nil
		}
		return os.WriteFile(path, []byte(updated), 0o644)
	})
}

// friendlyPath 把绝对路径转成用户友好的形式
// 优先显示 ~/myproject，其次显示相对路径
func friendlyPath(absPath string) string {
	home, err := os.UserHomeDir()
	if err == nil {
		home = filepath.Clean(home)
		abs := filepath.Clean(absPath)
		if strings.HasPrefix(abs, home) {
			rel := strings.TrimPrefix(abs, home)
			rel = strings.TrimPrefix(rel, string(filepath.Separator))
			if rel == "" {
				return "~"
			}
			return "~/" + filepath.ToSlash(rel)
		}
	}

	// 尝试转为相对当前目录
	if cwd, err := os.Getwd(); err == nil {
		if rel, err := filepath.Rel(cwd, absPath); err == nil && !strings.HasPrefix(rel, "..") {
			return filepath.ToSlash(rel)
		}
	}
	return absPath
}

// writeHelmTemplateSkeleton 生成自包含的 Helm chart templates。
// 所有基础设施组件（postgres、etcd）均以 yaml 文件形式存放，
// 不依赖任何第三方 chart dependency。
func writeHelmTemplateSkeleton(outputDir, name string) error {
	templatesDir := filepath.Join(outputDir, "deployments", name, "templates")
	if err := os.MkdirAll(templatesDir, 0o755); err != nil {
		return err
	}

	files := map[string]string{
		// ── postgres StatefulSet + Service ──────────────────────────
		filepath.Join(templatesDir, "postgres-statefulset.yaml"): fmt.Sprintf(`apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
    {{- include "%s.labels" . | nindent 4 }}
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: pass
            - name: POSTGRES_DB
              value: %s
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "user", "-d", "%s"]
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "user", "-d", "%s"]
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
`, name, name, name, name),

		// ── etcd Deployment + Service ────────────────────────────────
		filepath.Join(templatesDir, "etcd-deployment.yaml"): fmt.Sprintf(`apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
  namespace: {{ .Release.Namespace }}
  labels:
    app: etcd
    {{- include "%s.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.5.14
          command:
            - etcd
            - --listen-client-urls=http://0.0.0.0:2379
            - --advertise-client-urls=http://etcd:2379
            - --listen-peer-urls=http://0.0.0.0:2380
            - --initial-advertise-peer-urls=http://0.0.0.0:2380
            - --initial-cluster=default=http://0.0.0.0:2380
            - --data-dir=/etcd-data
          ports:
            - name: client
              containerPort: 2379
            - name: peer
              containerPort: 2380
          readinessProbe:
            httpGet:
              path: /health
              port: 2379
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 2379
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          volumeMounts:
            - name: etcd-data
              mountPath: /etcd-data
      volumes:
        - name: etcd-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: {{ .Release.Namespace }}
  labels:
    app: etcd
spec:
  selector:
    app: etcd
  ports:
    - name: client
      port: 2379
      targetPort: 2379
    - name: peer
      port: 2380
      targetPort: 2380
`, name),

		// ── 业务服务 deployment，含 initContainers ───────────────────
		// 注意：replaceInDir 会把 "project" 替换成项目名，
		// 这里用 {{ include }} 而不是写死，避免被替换
		filepath.Join(templatesDir, "deployment.yaml"): fmt.Sprintf(`apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "%s.fullname" . }}
  labels:
    {{- include "%s.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "%s.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "%s.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
        - name: wait-postgres
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done']
        - name: wait-etcd
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z etcd 2379; do echo waiting for etcd; sleep 2; done']
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "%s.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
`, name, name, name, name, name),

		// ── values.yaml 覆盖（含 env 和正确的 probe）────────────────
		filepath.Join(outputDir, "deployments", name, "values.yaml"): fmt.Sprintf(`# Default values for %s.
replicaCount: 1

image:
  repository: qingchun22/%s-arm64
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

livenessProbe:
  httpGet:
    path: /healthz
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /healthz
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}

# 环境变量 — 通过 deployment template 注入到容器
env:
  - name: DATABASE_URL
    value: "postgres://user:pass@postgres:5432/%s?sslmode=disable&search_path=public"
  - name: ETCD_ENDPOINTS
    value: "etcd:2379"
`, name, name, name),
	}

	for path, content := range files {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return fmt.Errorf("gen helm template %s: %w", path, err)
		}
	}
	return nil
}
