package scaffold

import (
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"unicode/utf8"
)

type InitOptions struct {
	Name         string
	Module       string
	OutputDir    string
	TemplateRoot string
	Force        bool
	Stdout       io.Writer
}

var (
	projectNamePattern = regexp.MustCompile(`^[a-z0-9-]+$`)
	copyEntries        = []string{
		".editorconfig",
		".gitignore",
		".gitlint",
		".golangci.yaml",
		".vscode",
		"build",
		"configs",
		"deployments",
		"docs",
		"githooks",
		"scripts",
		"templates",
		"tools",
		"docker-compose.yml",
		"LICENSE",
		"Makefile",
		"README.md",
	}
)

func InitProject(opts InitOptions) error {
	name := strings.TrimSpace(opts.Name)
	if name == "" {
		return errors.New("missing project name: use --name")
	}
	if !projectNamePattern.MatchString(name) {
		return fmt.Errorf("invalid project name %q: use lowercase letters, numbers, and '-' only", name)
	}
	module := strings.TrimSpace(opts.Module)
	if module == "" {
		module = name
	}
	if opts.Stdout == nil {
		opts.Stdout = io.Discard
	}

	templateRoot, err := resolveTemplateRoot(opts.TemplateRoot)
	if err != nil {
		return err
	}

	outputDir, err := resolveOutputDir(opts.OutputDir, name)
	if err != nil {
		return err
	}

	if err := ensureOutputDir(outputDir, opts.Force, name); err != nil {
		return err
	}

	for _, entry := range copyEntries {
		src := filepath.Join(templateRoot, entry)
		dst := filepath.Join(outputDir, entry)
		if err := copyPath(src, dst); err != nil {
			return fmt.Errorf("copy %s: %w", entry, err)
		}
	}

	if err := writeGoMod(filepath.Join(templateRoot, "go.mod"), filepath.Join(outputDir, "go.mod"), module); err != nil {
		return err
	}
	if err := writeServiceMain(filepath.Join(outputDir, "cmd", name, "main.go"), name); err != nil {
		return err
	}
	if err := writeComponentsConfig(filepath.Join(outputDir, "configs", "components.yaml"), name); err != nil {
		return err
	}
	if err := writeTestScript(filepath.Join(outputDir, "scripts", "test_api.sh"), name); err != nil {
		return err
	}
	if err := writeInternalSkeleton(outputDir, name, module); err != nil {
		return err
	}
	if err := writeAuthPackage(outputDir); err != nil {
		return err
	}
	if err := writeTestSkeleton(outputDir, name, module); err != nil {
		return err
	}
	if err := writeSnapshotSkeleton(outputDir, name); err != nil {
		return err
	}

	// 🔥 FIXED: gen project.env for deploy (raw string)
	configsPath := filepath.Join(outputDir, "configs", "project.env")
	envContent := fmt.Sprintf(`# Auto-generated by dtk init for deploy
PROJECT_NAME=%s
KUBE_NAMESPACE=%s
KUBE_CONTEXT=
MODULE_PATH=%s
REGISTRY_PREFIX=qingchun22
`, name, name, module)
	if err := os.WriteFile(configsPath, []byte(envContent), 0644); err != nil {
		return fmt.Errorf("gen project.env: %w", err)
	}

	if err := renameDir(filepath.Join(outputDir, "build", "docker", "helloworld"), filepath.Join(outputDir, "build", "docker", name)); err != nil {
		return err
	}
	if err := renameDir(filepath.Join(outputDir, "build", "docker", "dtk"), filepath.Join(outputDir, "build", "docker", name)); err != nil {
		// ignore if not exist
	}
	if err := renameDir(filepath.Join(outputDir, "deployments", "project"), filepath.Join(outputDir, "deployments", name)); err != nil {
		return err
	}

	if err := writeDockerfile(filepath.Join(outputDir, "build", "docker", name, "Dockerfile"), name); err != nil {
		return err
	}
	if err := writeBuildSh(filepath.Join(outputDir, "build", "docker", name, "build.sh"), name); err != nil {
		return err
	}

	replacements := map[string]string{
		"github.com/Ixecd/dev-toolkit": module,
		"dev-toolkit":                  name,
		"demo-svc":                     name, // 🔥 ADD: fix deploy.mk PROJECT_NAME等硬码
		"helloworld":                   name, // for docker/ if any
	}

	if err := replaceInDir(outputDir, replacements); err != nil {
		return fmt.Errorf("content replacement failed: %w", err)
	}

	if err := replaceInDir(filepath.Join(outputDir, "deployments"), map[string]string{
		"project": name,
	}); err != nil {
		return fmt.Errorf("fix helm chart templates: %w", err)
	}

	// after replaceInDir
	fixChartYAMLs(outputDir, name)

	// 🔥 ADD dir renames漏
	if err := renameDir(filepath.Join(outputDir, "deployments", "dev-toolkit"), filepath.Join(outputDir, "deployments", name)); err != nil {
		// ignore if not exist
	}
	if err := renameDir(filepath.Join(outputDir, "build", "docker", "dev-toolkit"), filepath.Join(outputDir, "build", "docker", name)); err != nil {
	}

	// 自动安装依赖
	if err := runInDir(outputDir, "git", "init"); err != nil {
		fmt.Fprintf(opts.Stdout, "[WARN] git init 失败，请手动执行\n")
	}
	if err := runInDir(outputDir, "git", "add", "."); err != nil {
		fmt.Fprintf(opts.Stdout, "[WARN] git add 失败，请手动执行\n")
	}
	if err := runInDir(outputDir, "git", "commit", "-m", "chore: init project by dtk"); err != nil {
		fmt.Fprintf(opts.Stdout, "[WARN] git commit 失败，请手动执行\n")
	}
	if err := runInDir(outputDir, "go", "get", "github.com/stretchr/testify@latest"); err != nil {
		fmt.Fprintf(opts.Stdout, "[WARN] go get testify 失败，请手动执行: go get github.com/stretchr/testify\n")
	}
	if err := runInDir(outputDir, "go", "mod", "tidy"); err != nil {
		fmt.Fprintf(opts.Stdout, "[WARN] go mod tidy 失败，请手动执行\n")
	}
	if err := runInDir(outputDir, "go", "get", "github.com/golang-jwt/jwt/v5"); err != nil {
		fmt.Fprintf(opts.Stdout, "[WARN] go get jwt 失败，请手动执行\n")
	}
	if err := runInDir(outputDir, "go", "get", "golang.org/x/crypto/bcrypt"); err != nil {
		fmt.Fprintf(opts.Stdout, "[WARN] go get bcrypt 失败，请手动执行\n")
	}

	// 友好路径显示（~/myproject 而不是绝对路径）
	friendly := friendlyPath(outputDir)

	fmt.Fprintf(opts.Stdout, "✅ 项目已成功生成！\n")
	fmt.Fprintf(opts.Stdout, "路径：%s\n", friendly)
	fmt.Fprintf(opts.Stdout, "模块名：%s\n", module)
	fmt.Fprintf(opts.Stdout, "入口服务：cmd/%s\n", name)
	fmt.Fprintf(opts.Stdout, "\n下一步执行：\n")
	fmt.Fprintf(opts.Stdout, "  cd %s\n", friendly)
	fmt.Fprintf(opts.Stdout, "  go mod tidy\n")
	fmt.Fprintf(opts.Stdout, "  make help          # 查看可用命令\n")
	return nil
}

func runInDir(dir string, name string, args ...string) error {
	cmd := exec.Command(name, args...)
	cmd.Dir = dir
	cmd.Stdout = io.Discard
	cmd.Stderr = io.Discard
	return cmd.Run()
}

func writeSnapshotSkeleton(outputDir, name string) error {
	readmeContent := fmt.Sprintf(`# %s 快照归档

命名格式：SNAPSHOT-{日期}-{里程碑}.md

示例：
- SNAPSHOT-2026-03-18-init.md        # 项目初始化
- SNAPSHOT-2026-03-18-feature-x.md  # 完成某个功能
`, name)

	readmePath := filepath.Join(outputDir, "snapshots", "README.md")
	if err := os.MkdirAll(filepath.Dir(readmePath), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(readmePath, []byte(readmeContent), 0o644); err != nil {
		return fmt.Errorf("gen snapshots/README.md: %w", err)
	}
	return nil
}

func writeTestSkeleton(outputDir, name, module string) error {
	camel := toCamel(name)

	e2eContent := fmt.Sprintf(`package e2e

import (
	"net/http"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const baseURL = "http://localhost:8080"

// TestE2E_%s 完整业务流程测试
// 前置：服务已启动（go run cmd/%s/main.go）
func TestE2E_%s(t *testing.T) {
	resp, err := http.Get(baseURL + "/healthz")
	require.NoError(t, err)
	defer resp.Body.Close()
	assert.Equal(t, http.StatusOK, resp.StatusCode)
}
`, camel, name, camel)

	integrationContent := `package integration

import (
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/stretchr/testify/assert"
)

// TestAPI_Healthz 不依赖外部服务，直接测试 handler 逻辑
func TestAPI_Healthz(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet, "/healthz", nil)
	w := httptest.NewRecorder()

	handler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("ok"))
	})
	handler.ServeHTTP(w, req)

	assert.Equal(t, http.StatusOK, w.Code)
	assert.Equal(t, "ok", w.Body.String())
}
`

	smokeContent := `package smoke

import (
	"net/http"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestSmoke_Health CI 部署后快速验证服务存活
// 前置：服务已启动
func TestSmoke_Health(t *testing.T) {
	resp, err := http.Get("http://localhost:8080/healthz")
	require.NoError(t, err)
	defer resp.Body.Close()
	assert.Equal(t, http.StatusOK, resp.StatusCode)
}
`

	files := map[string]string{
		filepath.Join(outputDir, "test", "e2e", "e2e_test.go"):         e2eContent,
		filepath.Join(outputDir, "test", "integration", "api_test.go"): integrationContent,
		filepath.Join(outputDir, "test", "smoke", "smoke_test.go"):     smokeContent,
	}

	for path, content := range files {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return fmt.Errorf("gen test file %s: %w", path, err)
		}
	}
	return nil
}

func toCamel(s string) string {
	parts := strings.Split(s, "-")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

func fixChartYAMLs(root, name string) {
	path := filepath.Join(root, "deployments", name, "Chart.yaml")
	data, err := os.ReadFile(path)
	if err != nil {
		return
	}
	updated := regexp.MustCompile(`(?s)dependencies:.*?(?=maintainers:|annotations:|type:|\z)`).ReplaceAllString(string(data), "dependencies: []")
	os.WriteFile(path, []byte(updated), 0644)
}

func resolveTemplateRoot(explicit string) (string, error) {
	if explicit != "" {
		return filepath.Abs(explicit)
	}
	if env := strings.TrimSpace(os.Getenv("DTK_TEMPLATE_ROOT")); env != "" {
		return filepath.Abs(env)
	}

	cwd, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("get cwd: %w", err)
	}
	if isTemplateRoot(cwd) {
		return cwd, nil
	}
	return "", errors.New("template root not found: use --template or set DTK_TEMPLATE_ROOT")
}

func isTemplateRoot(path string) bool {
	required := []string{
		"Makefile",
		filepath.Join("scripts", "make-rules", "common.mk"),
		filepath.Join("githooks", "pre-commit.sh"),
	}
	for _, item := range required {
		if _, err := os.Stat(filepath.Join(path, item)); err != nil {
			return false
		}
	}
	return true
}

func resolveOutputDir(explicit, name string) (string, error) {
	if explicit == "" {
		explicit = name
	}
	return filepath.Abs(explicit)
}

func ensureOutputDir(path string, force bool, name string) error {
	info, err := os.Stat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return os.MkdirAll(path, 0o755)
		}
		return err
	}
	if !info.IsDir() {
		return fmt.Errorf("输出路径存在但不是目录：%s", friendlyPath(path))
	}

	// === 新增严格检查：目录已存在时默认直接失败（保护用户项目）===
	entries, err := os.ReadDir(path)
	if err != nil {
		return err
	}
	if len(entries) > 0 || !force {
		// 即使是空目录，也建议用户加 --force（更明确）
		if force {
			// force=true 时允许继续（会覆盖）
			return nil
		}
		return fmt.Errorf("输出目录已存在：%s\n\n"+
			"   请使用其他路径，或加 --force 强制覆盖：\n"+
			"     dtk init --name %s --output %s --force",
			friendlyPath(path), name, friendlyPath(path)) // 这里 name 是 InitProject 里的局部变量
	}
	return nil
}

func copyPath(src, dst string) error {
	info, err := os.Stat(src)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	if shouldSkip(filepath.Base(src)) {
		return nil
	}
	if info.IsDir() {
		return copyDir(src, dst)
	}
	return copyFile(src, dst)
}

func copyDir(src, dst string) error {
	return filepath.WalkDir(src, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		base := filepath.Base(path)
		if shouldSkip(base) {
			if d.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		if d.Type()&os.ModeSymlink != 0 {
			return nil
		}
		rel, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}
		target := filepath.Join(dst, rel)
		if d.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		return copyFile(path, target)
	})
}

func copyFile(src, dst string) error {
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return err
	}
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()

	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()

	if _, err := io.Copy(out, in); err != nil {
		return err
	}
	return out.Close()
}

func writeGoMod(templatePath, outputPath, module string) error {
	data, err := os.ReadFile(templatePath)
	if err != nil {
		return fmt.Errorf("read go.mod template: %w", err)
	}
	lines := strings.Split(string(data), "\n")
	for i, line := range lines {
		if strings.HasPrefix(strings.TrimSpace(line), "module ") {
			lines[i] = "module " + module
		}
		if strings.HasPrefix(strings.TrimSpace(line), "go ") {
			lines[i] = "go 1.25"
		}
	}
	return os.WriteFile(outputPath, []byte(strings.Join(lines, "\n")), 0o644)
}

func writeServiceMain(path, name string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	content := fmt.Sprintf(`package main

import (
	"fmt"
	"net/http"
	"os"

	"github.com/Ixecd/dev-toolkit/internal/api"
)

func main() {
	port := getenv("PORT", "8080")

	h := api.NewHandler()
	mux := api.NewMux(h)

	addr := ":" + port
	fmt.Printf("service %%q listening on %%s\n", %q, addr)
	if err := http.ListenAndServe(addr, mux); err != nil {
		panic(err)
	}
}

func getenv(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}
`, name)
	return os.WriteFile(path, []byte(content), 0o644)
}

func writeComponentsConfig(path, name string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	content := fmt.Sprintf(`components:
  - name: %s
    port: 8080
    image: %s
`, name, name)
	return os.WriteFile(path, []byte(content), 0o644)
}

func writeTestScript(path, name string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	content := fmt.Sprintf(`#!/bin/bash
# API smoke test for %s
BASE="http://localhost:8080"

echo "=== Healthz ==="
curl -s "$BASE/healthz"
echo ""

echo "=== Unauthorized (expect 401) ==="
curl -s "$BASE/"
echo ""

echo "=== Authorized ==="
curl -s -H "Authorization: Bearer demo-token" "$BASE/"
echo ""
`, name)
	if err := os.WriteFile(path, []byte(content), 0o755); err != nil {
		return fmt.Errorf("gen test_api.sh: %w", err)
	}
	return nil
}

func renameDir(oldPath, newPath string) error {
	// 源目录不存在就跳过（模板里可能没有）
	if _, err := os.Stat(oldPath); err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}

	// === 目标已存在时自动清理（--force 模式下安全）===
	if _, err := os.Stat(newPath); err == nil {
		if err := os.RemoveAll(newPath); err != nil {
			return fmt.Errorf("清理旧目录失败 %s: %w", newPath, err)
		}
	}

	if err := os.MkdirAll(filepath.Dir(newPath), 0o755); err != nil {
		return err
	}
	return os.Rename(oldPath, newPath)
}

func isText(data []byte) bool {
	if !utf8.Valid(data) {
		return false
	}
	return !bytesContainsZero(data)
}

func bytesContainsZero(data []byte) bool {
	for _, b := range data {
		if b == 0 {
			return true
		}
	}
	return false
}

func shouldSkip(name string) bool {
	switch name {
	case ".git", ".cursor", "_output", "node_modules", ".DS_Store":
		return true
	default:
		return false
	}
}
func replaceInDir(root string, replacements map[string]string) error {
	// 目录不存在时优雅跳过
	// 常见于模板中没有 deployments/project 子目录的情况
	if _, err := os.Stat(root); err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}

	return filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		if d.Type()&os.ModeSymlink != 0 {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if !isText(data) {
			return nil
		}
		updated := string(data)
		for oldValue, newValue := range replacements {
			updated = strings.ReplaceAll(updated, oldValue, newValue)
		}
		if updated == string(data) {
			return nil
		}
		return os.WriteFile(path, []byte(updated), 0o644)
	})
}

// friendlyPath 把绝对路径转成用户友好的形式
// 优先显示 ~/myproject，其次显示相对路径
func friendlyPath(absPath string) string {
	home, err := os.UserHomeDir()
	if err == nil {
		home = filepath.Clean(home)
		abs := filepath.Clean(absPath)
		if strings.HasPrefix(abs, home) {
			rel := strings.TrimPrefix(abs, home)
			rel = strings.TrimPrefix(rel, string(filepath.Separator))
			if rel == "" {
				return "~"
			}
			return "~/" + filepath.ToSlash(rel)
		}
	}

	// 尝试转为相对当前目录
	if cwd, err := os.Getwd(); err == nil {
		if rel, err := filepath.Rel(cwd, absPath); err == nil && !strings.HasPrefix(rel, "..") {
			return filepath.ToSlash(rel)
		}
	}
	return absPath
}

func writeInternalSkeleton(outputDir, name, module string) error {
	files := map[string]string{
		// internal/pkg/code/code.go
		filepath.Join(outputDir, "internal", "pkg", "code", "code.go"): fmt.Sprintf(`package code

import "fmt"

type ErrorCode int

const (
	ErrUnknown      ErrorCode = 100000
	ErrInvalidArg   ErrorCode = 100001
	ErrUnauthorized ErrorCode = 100002
	ErrForbidden    ErrorCode = 100003
	ErrNotFound     ErrorCode = 100004
	ErrInternal     ErrorCode = 100005
)

var errorCodeMessages = map[ErrorCode]string{
	ErrUnknown:      "unknown error",
	ErrInvalidArg:   "invalid argument",
	ErrUnauthorized: "unauthorized",
	ErrForbidden:    "forbidden",
	ErrNotFound:     "not found",
	ErrInternal:     "internal server error",
}

func (e ErrorCode) ErrorCodeString() string {
	if msg, ok := errorCodeMessages[e]; ok {
		return msg
	}
	return fmt.Sprintf("error code %%d", int(e))
}
`),

		// internal/api/handler.go
		filepath.Join(outputDir, "internal", "api", "handler.go"): fmt.Sprintf(`package api

import (
	"encoding/json"
	"net/http"
)

type Handler struct{}

func NewHandler() *Handler {
	return &Handler{}
}

func (h *Handler) Healthz(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(http.StatusOK)
	w.Write([]byte("ok"))
}

func (h *Handler) Home(w http.ResponseWriter, r *http.Request) {
	json.NewEncoder(w).Encode(map[string]string{
		"service": %q,
		"status":  "ok",
	})
}
`, name),

		// internal/api/server.go
		filepath.Join(outputDir, "internal", "api", "server.go"): `package api

import "net/http"

func NewMux(h *Handler) *http.ServeMux {
	mux := http.NewServeMux()
	mux.HandleFunc("/healthz", h.Healthz)
	mux.HandleFunc("/", h.Home)
	return mux
}
`,
	}

	for path, content := range files {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return fmt.Errorf("gen internal file %s: %w", path, err)
		}
	}
	return nil
}

func writeDockerfile(path, name string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	content := fmt.Sprintf(`FROM golang:1.25-alpine AS builder

WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o %s ./cmd/%s

FROM alpine:3.20
WORKDIR /app
COPY --from=builder /app/%s .
EXPOSE 8080
CMD ["./%s"]
`, name, name, name, name)
	return os.WriteFile(path, []byte(content), 0o644)
}

func writeBuildSh(path, name string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	content := fmt.Sprintf(`#!/bin/bash
set -e
IMAGE_NAME=${1:-%s}
TAG=${2:-latest}
docker build -t "$IMAGE_NAME:$TAG" -f "$(dirname "$0")/Dockerfile" .
`, name)
	return os.WriteFile(path, []byte(content), 0o755)
}

func writeAuthPackage(outputDir string) error {
	authContent := "package auth\n\nimport (\n\t\"fmt\"\n\t\"time\"\n\n\t\"github.com/golang-jwt/jwt/v5\"\n\t\"golang.org/x/crypto/bcrypt\"\n)\n\nconst tokenExpiry = 24 * time.Hour\n\ntype Claims struct {\n\tUserID   int64  `json:\"user_id\"`\n\tUsername string `json:\"username\"`\n\tjwt.RegisteredClaims\n}\n\nfunc HashPassword(password string) (string, error) {\n\tbytes, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)\n\tif err != nil {\n\t\treturn \"\", fmt.Errorf(\"密码加密失败: %w\", err)\n\t}\n\treturn string(bytes), nil\n}\n\nfunc CheckPassword(password, hash string) bool {\n\treturn bcrypt.CompareHashAndPassword([]byte(hash), []byte(password)) == nil\n}\n\nfunc GenerateToken(userID int64, username, secret string) (string, error) {\n\tclaims := Claims{\n\t\tUserID:   userID,\n\t\tUsername: username,\n\t\tRegisteredClaims: jwt.RegisteredClaims{\n\t\t\tExpiresAt: jwt.NewNumericDate(time.Now().Add(tokenExpiry)),\n\t\t\tIssuedAt:  jwt.NewNumericDate(time.Now()),\n\t\t},\n\t}\n\ttoken := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)\n\treturn token.SignedString([]byte(secret))\n}\n\nfunc ParseToken(tokenStr, secret string) (*Claims, error) {\n\ttoken, err := jwt.ParseWithClaims(tokenStr, &Claims{}, func(t *jwt.Token) (interface{}, error) {\n\t\tif _, ok := t.Method.(*jwt.SigningMethodHMAC); !ok {\n\t\t\treturn nil, fmt.Errorf(\"非法签名方法: %v\", t.Header[\"alg\"])\n\t\t}\n\t\treturn []byte(secret), nil\n\t})\n\tif err != nil {\n\t\treturn nil, fmt.Errorf(\"token 解析失败: %w\", err)\n\t}\n\tclaims, ok := token.Claims.(*Claims)\n\tif !ok || !token.Valid {\n\t\treturn nil, fmt.Errorf(\"token 无效\")\n\t}\n\treturn claims, nil\n}\n"

	middlewareContent := "package auth\n\nimport (\n\t\"context\"\n\t\"net/http\"\n\t\"strings\"\n)\n\ntype contextKey string\n\nconst claimsKey contextKey = \"claims\"\n\nfunc JWTMiddleware(secret string, next http.HandlerFunc) http.HandlerFunc {\n\treturn func(w http.ResponseWriter, r *http.Request) {\n\t\theader := r.Header.Get(\"Authorization\")\n\t\tif header == \"\" {\n\t\t\thttp.Error(w, \"缺少 Authorization header\", http.StatusUnauthorized)\n\t\t\treturn\n\t\t}\n\t\tparts := strings.SplitN(header, \" \", 2)\n\t\tif len(parts) != 2 || parts[0] != \"Bearer\" {\n\t\t\thttp.Error(w, \"Authorization 格式错误\", http.StatusUnauthorized)\n\t\t\treturn\n\t\t}\n\t\tclaims, err := ParseToken(parts[1], secret)\n\t\tif err != nil {\n\t\t\thttp.Error(w, \"token 无效: \"+err.Error(), http.StatusUnauthorized)\n\t\t\treturn\n\t\t}\n\t\tctx := context.WithValue(r.Context(), claimsKey, claims)\n\t\tnext(w, r.WithContext(ctx))\n\t}\n}\n\nfunc GetClaims(r *http.Request) *Claims {\n\tclaims, _ := r.Context().Value(claimsKey).(*Claims)\n\treturn claims\n}\n"

	files := map[string]string{
		filepath.Join(outputDir, "internal", "auth", "auth.go"):       authContent,
		filepath.Join(outputDir, "internal", "auth", "middleware.go"): middlewareContent,
	}

	for path, content := range files {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return fmt.Errorf("gen auth file %s: %w", path, err)
		}
	}
	return nil
}
