package scaffold

import (
	"errors"
	"fmt"
	"io"
	"io/fs"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"unicode/utf8"
)

type InitOptions struct {
	Name         string
	Module       string
	OutputDir    string
	TemplateRoot string
	Force        bool
	WithFrontend bool
	Stdout       io.Writer
}

var (
	projectNamePattern = regexp.MustCompile(`^[a-z0-9-]+$`)
	copyEntries        = []string{
		".editorconfig",
		".gitignore",
		".gitlint",
		".golangci.yaml",
		".vscode",
		"build",
		"configs",
		"deployments",
		"docs",
		"githooks",
		"scripts",
		"templates",
		"tools",
		"docker-compose.yml",
		"LICENSE",
		"Makefile",
		"README.md",
	}
)

func InitProject(opts InitOptions) (err error) {
	name := strings.TrimSpace(opts.Name)
	if name == "" {
		return errors.New("missing project name: use --name")
	}
	if !projectNamePattern.MatchString(name) {
		return fmt.Errorf("invalid project name %q: use lowercase letters, numbers, and '-' only", name)
	}
	module := strings.TrimSpace(opts.Module)
	if module == "" {
		module = name
	}
	if opts.Stdout == nil {
		opts.Stdout = io.Discard
	}

	templateRoot, err := resolveTemplateRoot(opts.TemplateRoot)
	if err != nil {
		return err
	}

	outputDir, err := resolveOutputDir(opts.OutputDir, name)
	if err != nil {
		return err
	}

	// 记录目录是否由本次 init 创建
	// --force 时目录已存在，失败不能删（里面可能有用户文件）
	_, statErr := os.Stat(outputDir)
	createdByUs := os.IsNotExist(statErr) && !opts.Force

	if err = ensureOutputDir(outputDir, opts.Force, name); err != nil {
		return err
	}

	// 初始化失败时自动清理半成品目录
	defer func() {
		if err != nil && createdByUs {
			slog.Debug("初始化失败，清理半成品目录", "dir", outputDir)
			if removeErr := os.RemoveAll(outputDir); removeErr != nil {
				slog.Debug("清理失败", "dir", outputDir, "err", removeErr)
				return
			}
			fmt.Fprintf(opts.Stdout, "⚠️  初始化失败，已自动清理：%s\n", friendlyPath(outputDir))
		}
	}()

	for _, entry := range copyEntries {
		src := filepath.Join(templateRoot, entry)
		dst := filepath.Join(outputDir, entry)
		if err := copyPath(src, dst); err != nil {
			return fmt.Errorf("copy %s: %w", entry, err)
		}
	}

	if err := writeGoMod(filepath.Join(templateRoot, "go.mod"), filepath.Join(outputDir, "go.mod"), module); err != nil {
		return err
	}
	if err := writeServiceMain(filepath.Join(outputDir, "cmd", name, "main.go"), name); err != nil {
		return err
	}
	if err := writeComponentsConfig(filepath.Join(outputDir, "configs", "components.yaml"), name); err != nil {
		return err
	}
	if err := writeTestScript(filepath.Join(outputDir, "scripts", "test_api.sh"), name); err != nil {
		return err
	}
	if err := writeInternalSkeleton(outputDir, name, module); err != nil {
		return err
	}
	if err := writeAuthPackage(outputDir); err != nil {
		return err
	}
	if err := writeMetricsSkeleton(outputDir, name); err != nil {
		return err
	}
	if err := writeMonitoringSkeleton(outputDir, name); err != nil {
		return err
	}
	if err := writeTestSkeleton(outputDir, name, module); err != nil {
		return err
	}
	if err := writeSnapshotSkeleton(outputDir, name); err != nil {
		return err
	}
	if err := writeSwaggerSpec(outputDir, name); err != nil {
		return err
	}

	// 🔥 FIXED: gen project.env for deploy (raw string)
	configsPath := filepath.Join(outputDir, "configs", "project.env")
	envContent := fmt.Sprintf(`# Auto-generated by dtk init for deploy
PROJECT_NAME=%s
KUBE_NAMESPACE=%s
KUBE_CONTEXT=
MODULE_PATH=%s
REGISTRY_PREFIX=qingchun22
`, name, name, module)
	if err := os.WriteFile(configsPath, []byte(envContent), 0644); err != nil {
		return fmt.Errorf("gen project.env: %w", err)
	}

	if err := renameDir(filepath.Join(outputDir, "build", "docker", "helloworld"), filepath.Join(outputDir, "build", "docker", name)); err != nil {
		return err
	}
	if err := renameDir(filepath.Join(outputDir, "build", "docker", "dtk"), filepath.Join(outputDir, "build", "docker", name)); err != nil {
		// ignore if not exist
	}
	if err := renameDir(filepath.Join(outputDir, "deployments", "project"), filepath.Join(outputDir, "deployments", name)); err != nil {
		return err
	}

	if err := writeDockerfile(filepath.Join(outputDir, "build", "docker", name, "Dockerfile"), name); err != nil {
		return err
	}
	if err := writeBuildSh(filepath.Join(outputDir, "build", "docker", name, "build.sh"), name); err != nil {
		return err
	}

	replacements := map[string]string{
		"github.com/Ixecd/dev-toolkit": module,
		"dev-toolkit":                  name,
	}

	if err := replaceInDir(outputDir, replacements); err != nil {
		return fmt.Errorf("content replacement failed: %w", err)
	}

	if err := replaceInDir(filepath.Join(outputDir, "deployments"), map[string]string{
		"project": name,
	}); err != nil {
		return fmt.Errorf("fix helm chart templates: %w", err)
	}

	// after replaceInDir
	fixChartYAMLs(outputDir, name)

	// 🔥 ADD dir renames漏
	if err := renameDir(filepath.Join(outputDir, "deployments", "dev-toolkit"), filepath.Join(outputDir, "deployments", name)); err != nil {
		// ignore if not exist
	}
	if err := renameDir(filepath.Join(outputDir, "build", "docker", "dev-toolkit"), filepath.Join(outputDir, "build", "docker", name)); err != nil {
	}

	// 自动安装依赖
	if err := runInDir(outputDir, "git", "init"); err != nil {
		fmt.Fprintf(opts.Stdout, "[WARN] git init 失败，请手动执行\n")
	}
	if err := runInDir(outputDir, "git", "add", "."); err != nil {
		fmt.Fprintf(opts.Stdout, "[WARN] git add 失败，请手动执行\n")
	}
	if err := runInDir(outputDir, "git", "commit", "-m", "chore: init project by dtk"); err != nil {
		fmt.Fprintf(opts.Stdout, "[WARN] git commit 失败，请手动执行\n")
	}
	if err := runInDir(outputDir, "go", "get", "github.com/stretchr/testify@latest"); err != nil {
		fmt.Fprintf(opts.Stdout, "[WARN] go get testify 失败，请手动执行: go get github.com/stretchr/testify\n")
	}
	if err := runInDir(outputDir, "go", "get", "github.com/golang-jwt/jwt/v5"); err != nil {
		fmt.Fprintf(opts.Stdout, "[WARN] go get jwt 失败，请手动执行\n")
	}
	if err := runInDir(outputDir, "go", "get", "golang.org/x/crypto/bcrypt"); err != nil {
		fmt.Fprintf(opts.Stdout, "[WARN] go get bcrypt 失败，请手动执行\n")
	}
	if err := runInDir(outputDir, "go", "get", "github.com/prometheus/client_golang/prometheus"); err != nil {
		fmt.Fprintf(opts.Stdout, "[WARN] go get prometheus 失败，请手动执行\n")
	}
	if err := runInDir(outputDir, "go", "mod", "tidy"); err != nil {
		fmt.Fprintf(opts.Stdout, "[WARN] go mod tidy 失败，请手动执行\n")
	}

	// 友好路径显示（~/myproject 而不是绝对路径）
	friendly := friendlyPath(outputDir)

	fmt.Fprintf(opts.Stdout, "✅ 项目已成功生成！\n\n")
	fmt.Fprintf(opts.Stdout, "  路径    %s\n", friendly)
	fmt.Fprintf(opts.Stdout, "  模块    %s\n", module)
	fmt.Fprintf(opts.Stdout, "  入口    cmd/%s\n\n", name)
	fmt.Fprintf(opts.Stdout, "下一步：\n")
	fmt.Fprintf(opts.Stdout, "  cd %s\n", friendly)
	fmt.Fprintf(opts.Stdout, "  make tools   # 安装所有工具\n")
	fmt.Fprintf(opts.Stdout, "  make build   # 编译\n")
	fmt.Fprintf(opts.Stdout, "  make test    # 测试\n")

	if opts.WithFrontend {
		if err := writeFrontendSkeleton(outputDir, name); err != nil {
			return fmt.Errorf("gen frontend: %w", err)
		}
		fmt.Fprintf(opts.Stdout, "  cd %s/frontend && npm install && npm run dev  # 前端\n", friendly)
	}
	return nil
}

func runInDir(dir string, name string, args ...string) error {
	slog.Debug("执行命令", "cmd", name, "args", args, "dir", dir)
	cmd := exec.Command(name, args...)
	cmd.Dir = dir
	cmd.Stdout = io.Discard
	var errBuf strings.Builder
	cmd.Stderr = &errBuf
	err := cmd.Run()
	if err != nil {
		slog.Debug("命令执行失败",
			"cmd", name,
			"args", args,
			"stderr", strings.TrimSpace(errBuf.String()),
			"err", err,
		)
	}
	return err
}

func writeSnapshotSkeleton(outputDir, name string) error {
	readmeContent := fmt.Sprintf(`# %s 快照归档

命名格式：SNAPSHOT-{日期}-{里程碑}.md

示例：
- SNAPSHOT-2026-03-18-init.md        # 项目初始化
- SNAPSHOT-2026-03-18-feature-x.md  # 完成某个功能
`, name)

	readmePath := filepath.Join(outputDir, "snapshots", "README.md")
	if err := os.MkdirAll(filepath.Dir(readmePath), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(readmePath, []byte(readmeContent), 0o644); err != nil {
		return fmt.Errorf("gen snapshots/README.md: %w", err)
	}
	return nil
}

func writeTestSkeleton(outputDir, name, module string) error {
	camel := toCamel(name)

	e2eContent := fmt.Sprintf(`//go:build e2e

package e2e

import (
	"net/http"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const baseURL = "http://localhost:8080"

// TestE2E_%s 完整业务流程测试
// 前置：服务已启动（go run cmd/%s/main.go）
func TestE2E_%s(t *testing.T) {
	resp, err := http.Get(baseURL + "/healthz")
	require.NoError(t, err)
	defer resp.Body.Close()
	assert.Equal(t, http.StatusOK, resp.StatusCode)
}
`, camel, name, camel)

	integrationContent := `package integration

import (
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/stretchr/testify/assert"
)

// TestAPI_Healthz 不依赖外部服务，直接测试 handler 逻辑
func TestAPI_Healthz(t *testing.T) {
	req := httptest.NewRequest(http.MethodGet, "/healthz", nil)
	w := httptest.NewRecorder()

	handler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("ok"))
	})
	handler.ServeHTTP(w, req)

	assert.Equal(t, http.StatusOK, w.Code)
	assert.Equal(t, "ok", w.Body.String())
}
`

	smokeContent := `//go:build e2e

package smoke

import (
	"net/http"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestSmoke_Health CI 部署后快速验证服务存活
// 前置：服务已启动
func TestSmoke_Health(t *testing.T) {
	resp, err := http.Get("http://localhost:8080/healthz")
	require.NoError(t, err)
	defer resp.Body.Close()
	assert.Equal(t, http.StatusOK, resp.StatusCode)
}
`

	files := map[string]string{
		filepath.Join(outputDir, "test", "e2e", "e2e_test.go"):         e2eContent,
		filepath.Join(outputDir, "test", "integration", "api_test.go"): integrationContent,
		filepath.Join(outputDir, "test", "smoke", "smoke_test.go"):     smokeContent,
	}

	for path, content := range files {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return fmt.Errorf("gen test file %s: %w", path, err)
		}
	}
	return nil
}

func toCamel(s string) string {
	parts := strings.Split(s, "-")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

func fixChartYAMLs(root, name string) {
	path := filepath.Join(root, "deployments", name, "Chart.yaml")
	data, err := os.ReadFile(path)
	if err != nil {
		return
	}
	updated := regexp.MustCompile(`(?s)dependencies:.*?(?=maintainers:|annotations:|type:|\z)`).ReplaceAllString(string(data), "dependencies: []")
	os.WriteFile(path, []byte(updated), 0644)
}

func resolveTemplateRoot(explicit string) (string, error) {
	if explicit != "" {
		return filepath.Abs(explicit)
	}
	if env := strings.TrimSpace(os.Getenv("DTK_TEMPLATE_ROOT")); env != "" {
		return filepath.Abs(env)
	}

	cwd, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("get cwd: %w", err)
	}
	if isTemplateRoot(cwd) {
		return cwd, nil
	}
	return "", errors.New("template root not found: use --template or set DTK_TEMPLATE_ROOT")
}

func isTemplateRoot(path string) bool {
	required := []string{
		"Makefile",
		filepath.Join("scripts", "make-rules", "common.mk"),
		filepath.Join("githooks", "pre-commit.sh"),
	}
	for _, item := range required {
		if _, err := os.Stat(filepath.Join(path, item)); err != nil {
			return false
		}
	}
	return true
}

func resolveOutputDir(explicit, name string) (string, error) {
	if explicit == "" {
		explicit = name
	}
	return filepath.Abs(explicit)
}

func ensureOutputDir(path string, force bool, name string) error {
	info, err := os.Stat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return os.MkdirAll(path, 0o755)
		}
		return err
	}
	if !info.IsDir() {
		return fmt.Errorf("输出路径存在但不是目录：%s", friendlyPath(path))
	}

	// === 新增严格检查：目录已存在时默认直接失败（保护用户项目）===
	entries, err := os.ReadDir(path)
	if err != nil {
		return err
	}
	if len(entries) > 0 || !force {
		// 即使是空目录，也建议用户加 --force（更明确）
		if force {
			// force=true 时允许继续（会覆盖）
			return nil
		}
		return fmt.Errorf("输出目录已存在：%s\n\n"+
			"   请使用其他路径，或加 --force 强制覆盖：\n"+
			"     dtk init --name %s --output %s --force",
			friendlyPath(path), name, friendlyPath(path)) // 这里 name 是 InitProject 里的局部变量
	}
	return nil
}

func copyPath(src, dst string) error {
	info, err := os.Stat(src)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	if shouldSkip(filepath.Base(src)) {
		return nil
	}
	if info.IsDir() {
		return copyDir(src, dst)
	}
	return copyFile(src, dst)
}

func copyDir(src, dst string) error {
	return filepath.WalkDir(src, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		base := filepath.Base(path)
		if shouldSkip(base) {
			if d.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		if d.Type()&os.ModeSymlink != 0 {
			return nil
		}
		rel, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}
		target := filepath.Join(dst, rel)
		if d.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		return copyFile(path, target)
	})
}

func copyFile(src, dst string) error {
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return err
	}
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()

	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()

	if _, err := io.Copy(out, in); err != nil {
		return err
	}
	return out.Close()
}

func writeGoMod(templatePath, outputPath, module string) error {
	data, err := os.ReadFile(templatePath)
	if err != nil {
		return fmt.Errorf("read go.mod template: %w", err)
	}
	lines := strings.Split(string(data), "\n")
	for i, line := range lines {
		if strings.HasPrefix(strings.TrimSpace(line), "module ") {
			lines[i] = "module " + module
		}
		if strings.HasPrefix(strings.TrimSpace(line), "go ") {
			lines[i] = "go 1.25"
		}
	}
	return os.WriteFile(outputPath, []byte(strings.Join(lines, "\n")), 0o644)
}

func writeServiceMain(path, name string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	content := fmt.Sprintf(`package main

import (
	"fmt"
	"net/http"
	"os"

	"github.com/Ixecd/dev-toolkit/internal/api"
)

func main() {
	port := getenv("PORT", "8080")

	h := api.NewHandler()
	mux := api.NewMux(h)

	addr := ":" + port
	fmt.Printf("service %%q listening on %%s\n", %q, addr)
	if err := http.ListenAndServe(addr, mux); err != nil {
		panic(err)
	}
}

func getenv(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}
`, name)
	return os.WriteFile(path, []byte(content), 0o644)
}

func writeComponentsConfig(path, name string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	content := fmt.Sprintf(`components:
  - name: %s
    port: 8080
    image: %s
`, name, name)
	return os.WriteFile(path, []byte(content), 0o644)
}

func writeTestScript(path, name string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	content := fmt.Sprintf(`#!/bin/bash
# API smoke test for %s
BASE="http://localhost:8080"

echo "=== Healthz ==="
curl -s "$BASE/healthz"
echo ""

echo "=== Unauthorized (expect 401) ==="
curl -s "$BASE/"
echo ""

echo "=== Authorized ==="
curl -s -H "Authorization: Bearer demo-token" "$BASE/"
echo ""
`, name)
	if err := os.WriteFile(path, []byte(content), 0o755); err != nil {
		return fmt.Errorf("gen test_api.sh: %w", err)
	}
	return nil
}

func renameDir(oldPath, newPath string) error {
	// 源目录不存在就跳过（模板里可能没有）
	if _, err := os.Stat(oldPath); err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}

	// === 目标已存在时自动清理（--force 模式下安全）===
	if _, err := os.Stat(newPath); err == nil {
		if err := os.RemoveAll(newPath); err != nil {
			return fmt.Errorf("清理旧目录失败 %s: %w", newPath, err)
		}
	}

	if err := os.MkdirAll(filepath.Dir(newPath), 0o755); err != nil {
		return err
	}
	return os.Rename(oldPath, newPath)
}

func isText(data []byte) bool {
	if !utf8.Valid(data) {
		return false
	}
	return !bytesContainsZero(data)
}

func bytesContainsZero(data []byte) bool {
	for _, b := range data {
		if b == 0 {
			return true
		}
	}
	return false
}

func shouldSkip(name string) bool {
	switch name {
	case ".git", ".cursor", "_output", "node_modules", ".DS_Store":
		return true
	default:
		return false
	}
}
func replaceInDir(root string, replacements map[string]string) error {
	// 目录不存在时优雅跳过
	// 常见于模板中没有 deployments/project 子目录的情况
	if _, err := os.Stat(root); err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}

	return filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		if d.Type()&os.ModeSymlink != 0 {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if !isText(data) {
			return nil
		}
		updated := string(data)
		for oldValue, newValue := range replacements {
			updated = strings.ReplaceAll(updated, oldValue, newValue)
		}
		if updated == string(data) {
			return nil
		}
		return os.WriteFile(path, []byte(updated), 0o644)
	})
}

// friendlyPath 把绝对路径转成用户友好的形式
// 优先显示 ~/myproject，其次显示相对路径
func friendlyPath(absPath string) string {
	home, err := os.UserHomeDir()
	if err == nil {
		home = filepath.Clean(home)
		abs := filepath.Clean(absPath)
		if strings.HasPrefix(abs, home) {
			rel := strings.TrimPrefix(abs, home)
			rel = strings.TrimPrefix(rel, string(filepath.Separator))
			if rel == "" {
				return "~"
			}
			return "~/" + filepath.ToSlash(rel)
		}
	}

	// 尝试转为相对当前目录
	if cwd, err := os.Getwd(); err == nil {
		if rel, err := filepath.Rel(cwd, absPath); err == nil && !strings.HasPrefix(rel, "..") {
			return filepath.ToSlash(rel)
		}
	}
	return absPath
}

func writeInternalSkeleton(outputDir, name, module string) error {
	files := map[string]string{
		// internal/pkg/code/code.go
		filepath.Join(outputDir, "internal", "pkg", "code", "code.go"): fmt.Sprintf(`package code

import "fmt"

type ErrorCode int

const (
	ErrUnknown      ErrorCode = 100000
	ErrInvalidArg   ErrorCode = 100001
	ErrUnauthorized ErrorCode = 100002
	ErrForbidden    ErrorCode = 100003
	ErrNotFound     ErrorCode = 100004
	ErrInternal     ErrorCode = 100005
)

var errorCodeMessages = map[ErrorCode]string{
	ErrUnknown:      "unknown error",
	ErrInvalidArg:   "invalid argument",
	ErrUnauthorized: "unauthorized",
	ErrForbidden:    "forbidden",
	ErrNotFound:     "not found",
	ErrInternal:     "internal server error",
}

func (e ErrorCode) ErrorCodeString() string {
	if msg, ok := errorCodeMessages[e]; ok {
		return msg
	}
	return fmt.Sprintf("error code %%d", int(e))
}
`),

		// internal/api/handler.go
		filepath.Join(outputDir, "internal", "api", "handler.go"): fmt.Sprintf(`package api

import (
	"encoding/json"
	"net/http"
)

type Handler struct{}

func NewHandler() *Handler {
	return &Handler{}
}

func (h *Handler) Healthz(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(http.StatusOK)
	w.Write([]byte("ok"))
}

func (h *Handler) Home(w http.ResponseWriter, r *http.Request) {
	json.NewEncoder(w).Encode(map[string]string{
		"service": %q,
		"status":  "ok",
	})
}
`, name),

		// internal/api/server.go
		filepath.Join(outputDir, "internal", "api", "server.go"): `package api

import "net/http"

func NewMux(h *Handler) *http.ServeMux {
	mux := http.NewServeMux()
	mux.HandleFunc("/healthz", h.Healthz)
	mux.HandleFunc("/", h.Home)
	return mux
}
`,
	}

	for path, content := range files {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return fmt.Errorf("gen internal file %s: %w", path, err)
		}
	}
	return nil
}

func writeDockerfile(path, name string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	content := fmt.Sprintf(`FROM golang:1.25-alpine AS builder

WORKDIR /app
COPY . .
RUN go env -w GOPROXY=https://goproxy.cn,direct
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -o %s ./cmd/%s

FROM alpine:3.20
WORKDIR /app
COPY --from=builder /app/%s .
EXPOSE 8080
CMD ["./%s"]
`, name, name, name, name)
	return os.WriteFile(path, []byte(content), 0o644)
}

func writeBuildSh(path, name string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	content := fmt.Sprintf(`#!/bin/bash
set -e
IMAGE_NAME=${1:-%s}
TAG=${2:-latest}
docker build -t "$IMAGE_NAME:$TAG" -f "$(dirname "$0")/Dockerfile" .
`, name)
	return os.WriteFile(path, []byte(content), 0o755)
}

func writeAuthPackage(outputDir string) error {
	authContent := "package auth\n\nimport (\n\t\"fmt\"\n\t\"time\"\n\n\t\"github.com/golang-jwt/jwt/v5\"\n\t\"golang.org/x/crypto/bcrypt\"\n)\n\nconst tokenExpiry = 24 * time.Hour\n\ntype Claims struct {\n\tUserID   int64  `json:\"user_id\"`\n\tUsername string `json:\"username\"`\n\tjwt.RegisteredClaims\n}\n\nfunc HashPassword(password string) (string, error) {\n\tbytes, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)\n\tif err != nil {\n\t\treturn \"\", fmt.Errorf(\"密码加密失败: %w\", err)\n\t}\n\treturn string(bytes), nil\n}\n\nfunc CheckPassword(password, hash string) bool {\n\treturn bcrypt.CompareHashAndPassword([]byte(hash), []byte(password)) == nil\n}\n\nfunc GenerateToken(userID int64, username, secret string) (string, error) {\n\tclaims := Claims{\n\t\tUserID:   userID,\n\t\tUsername: username,\n\t\tRegisteredClaims: jwt.RegisteredClaims{\n\t\t\tExpiresAt: jwt.NewNumericDate(time.Now().Add(tokenExpiry)),\n\t\t\tIssuedAt:  jwt.NewNumericDate(time.Now()),\n\t\t},\n\t}\n\ttoken := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)\n\treturn token.SignedString([]byte(secret))\n}\n\nfunc ParseToken(tokenStr, secret string) (*Claims, error) {\n\ttoken, err := jwt.ParseWithClaims(tokenStr, &Claims{}, func(t *jwt.Token) (interface{}, error) {\n\t\tif _, ok := t.Method.(*jwt.SigningMethodHMAC); !ok {\n\t\t\treturn nil, fmt.Errorf(\"非法签名方法: %v\", t.Header[\"alg\"])\n\t\t}\n\t\treturn []byte(secret), nil\n\t})\n\tif err != nil {\n\t\treturn nil, fmt.Errorf(\"token 解析失败: %w\", err)\n\t}\n\tclaims, ok := token.Claims.(*Claims)\n\tif !ok || !token.Valid {\n\t\treturn nil, fmt.Errorf(\"token 无效\")\n\t}\n\treturn claims, nil\n}\n"

	middlewareContent := "package auth\n\nimport (\n\t\"context\"\n\t\"net/http\"\n\t\"strings\"\n)\n\ntype contextKey string\n\nconst claimsKey contextKey = \"claims\"\n\nfunc JWTMiddleware(secret string, next http.HandlerFunc) http.HandlerFunc {\n\treturn func(w http.ResponseWriter, r *http.Request) {\n\t\theader := r.Header.Get(\"Authorization\")\n\t\tif header == \"\" {\n\t\t\thttp.Error(w, \"缺少 Authorization header\", http.StatusUnauthorized)\n\t\t\treturn\n\t\t}\n\t\tparts := strings.SplitN(header, \" \", 2)\n\t\tif len(parts) != 2 || parts[0] != \"Bearer\" {\n\t\t\thttp.Error(w, \"Authorization 格式错误\", http.StatusUnauthorized)\n\t\t\treturn\n\t\t}\n\t\tclaims, err := ParseToken(parts[1], secret)\n\t\tif err != nil {\n\t\t\thttp.Error(w, \"token 无效: \"+err.Error(), http.StatusUnauthorized)\n\t\t\treturn\n\t\t}\n\t\tctx := context.WithValue(r.Context(), claimsKey, claims)\n\t\tnext(w, r.WithContext(ctx))\n\t}\n}\n\nfunc GetClaims(r *http.Request) *Claims {\n\tclaims, _ := r.Context().Value(claimsKey).(*Claims)\n\treturn claims\n}\n"

	files := map[string]string{
		filepath.Join(outputDir, "internal", "auth", "auth.go"):       authContent,
		filepath.Join(outputDir, "internal", "auth", "middleware.go"): middlewareContent,
		filepath.Join(outputDir, "internal", "auth", "rbac.go"): `package auth

import (
	"context"
	"net/http"
)

// PermissionChecker 权限检查接口，业务层实现
type PermissionChecker interface {
	HasPermission(ctx context.Context, userID int64, permission string) (bool, error)
}

// RBACMiddleware 权限中间件，需要先经过 JWTMiddleware
func RBACMiddleware(checker PermissionChecker, permission string, next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		claims := GetClaims(r)
		if claims == nil {
			http.Error(w, "unauthorized", http.StatusUnauthorized)
			return
		}
		ok, err := checker.HasPermission(r.Context(), claims.UserID, permission)
		if err != nil {
			http.Error(w, "权限查询失败", http.StatusInternalServerError)
			return
		}
		if !ok {
			http.Error(w, "权限不足", http.StatusForbidden)
			return
		}
		next(w, r)
	}
}
`,
	}

	for path, content := range files {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return fmt.Errorf("gen auth file %s: %w", path, err)
		}
	}
	return nil
}

func writeSwaggerSpec(outputDir, name string) error {
	content := fmt.Sprintf(`swagger: "2.0"
info:
  title: %s API
  description: %s 服务 API 文档
  version: "1.0.0"

host: localhost:8080
basePath: /
schemes:
  - http

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: "格式: Bearer <access_token>"

consumes:
  - application/json
produces:
  - application/json

definitions:
  Response:
    type: object
    properties:
      code:
        type: integer
      message:
        type: string
      data:
        description: 成功数据

paths:
  /healthz:
    get:
      tags:
        - System
      summary: 健康检查
      produces:
        - text/plain
      responses:
        200:
          description: ok

  /:
    get:
      tags:
        - System
      summary: 服务信息
      security:
        - Bearer: []
      responses:
        200:
          description: 服务信息
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  service:
                    type: string
                    example: %q
                  status:
                    type: string
                    example: "ok"
        401:
          description: 未认证
          schema:
            $ref: "#/definitions/Response"
`, name, name, name)

	path := filepath.Join(outputDir, "docs", "swagger.yaml")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

func writeMetricsSkeleton(outputDir, name string) error {
	content := fmt.Sprintf(`package metrics

import "github.com/prometheus/client_golang/prometheus"

var (
	// HTTP 请求总数
	HTTPRequestTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "%s_http_request_total",
		Help: "Total number of HTTP requests",
	}, []string{"method", "path", "status"})

	// HTTP 请求延迟
	HTTPRequestDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "%s_http_request_duration_seconds",
		Help:    "HTTP request duration in seconds",
		Buckets: prometheus.DefBuckets,
	}, []string{"method", "path"})

	// 业务错误总数
	BusinessErrorTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "%s_business_error_total",
		Help: "Total number of business errors",
	}, []string{"code"})
)

func Init() {
	prometheus.MustRegister(
		HTTPRequestTotal,
		HTTPRequestDuration,
		BusinessErrorTotal,
	)
}
`, name, name, name)

	path := filepath.Join(outputDir, "internal", "metrics", "metrics.go")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

func writeMonitoringSkeleton(outputDir, name string) error {
	// 告警规则
	rulesContent := fmt.Sprintf(`groups:
  - name: %s
    rules:
      # 服务不可达
      - alert: ServiceDown
        expr: up{job="%s"} == 0
        for: 1m
        labels:
          severity: critical
          service: %s
        annotations:
          description: "%s 已停止响应，请立即检查"

      # HTTP 错误率过高（5xx）
      - alert: HighErrorRate
        expr: increase(%s_http_request_total{status=~"5.."}[5m]) > 10
        for: 2m
        labels:
          severity: warning
          service: %s
        annotations:
          description: "%s 过去5分钟 5xx 错误超过10次"

      # 请求延迟过高
      - alert: HighLatency
        expr: histogram_quantile(0.99, rate(%s_http_request_duration_seconds_bucket[5m])) > 1
        for: 2m
        labels:
          severity: warning
          service: %s
        annotations:
          description: "%s P99 延迟超过1秒"
`, name, name, name, name, name, name, name, name, name, name)

	prometheusContent := fmt.Sprintf(`global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: '%s'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:8080']
        labels:
          environment: "local-dev"
          service: "%s"
`, name, name)

	// Alertmanager 配置骨架
	alertmanagerContent := `# Alertmanager 配置
# 文档: https://prometheus.io/docs/alerting/latest/configuration/
# 注意: bot_token 等敏感信息不要提交到 git，通过环境变量或外部 secret 注入

global:
  resolve_timeout: 5m

route:
  receiver: 'telegram'
  group_by: ['alertname', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: '<YOUR_BOT_TOKEN>'
        chat_id: <YOUR_CHAT_ID>
        message: |
          🚨 *{{ .GroupLabels.alertname }}*
          {{ range .Alerts }}
          *状态*: {{ .Status }}
          *服务*: {{ .Labels.service }}
          *描述*: {{ .Annotations.description }}
          {{ end }}
        parse_mode: 'Markdown'
`

	readmeContent := fmt.Sprintf(`# %s 监控告警

## 目录结构

`+"```"+`
monitoring/
├── prometheus/
│   ├── prometheus.yml         # Prometheus 配置
│   └── rules/%s.yml          # 告警规则
├── alertmanager/
│   └── alertmanager.yml       # Alertmanager 配置（bot_token 勿提交）
└── grafana/
    ├── dashboards/%s.json     # Grafana Dashboard
    └── provisioning/
        ├── dashboards/dashboard.yml
        └── datasources/prometheus.yml
`+"```"+`

## 本地启动

`+"```bash"+`
# 1. Prometheus
prometheus --config.file=monitoring/prometheus/prometheus.yml

# 2. Alertmanager
alertmanager --config.file=monitoring/alertmanager/alertmanager.yml

# 3. Grafana（Docker）
docker run -d \
  -p 3000:3000 \
  -v $(pwd)/monitoring/grafana/provisioning:/etc/grafana/provisioning \
  -v $(pwd)/monitoring/grafana/dashboards:/etc/grafana/dashboards \
  grafana/grafana
`+"```"+`

## 告警规则

| 告警名 | 级别 | 触发条件 |
|--------|------|---------|
| ServiceDown | critical | 服务不可达超过1分钟 |
| HighErrorRate | warning | 5分钟内5xx超过10次 |
| HighLatency | warning | P99延迟超过1秒 |

## 注意

- alertmanager.yml 含 bot_token，已加入 .gitignore，勿提交
- 生产环境通过 K8s Secret 注入敏感配置
`, name, name, name)

	files := map[string]string{
		filepath.Join(outputDir, "monitoring", "prometheus", "rules", name+".yml"): rulesContent,
		filepath.Join(outputDir, "monitoring", "alertmanager", "alertmanager.yml"): alertmanagerContent,
		filepath.Join(outputDir, "monitoring", "prometheus", "prometheus.yml"):     prometheusContent,
		// Grafana datasource 配置
		filepath.Join(outputDir, "monitoring", "grafana", "provisioning", "datasources", "prometheus.yml"): `apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
`,

		// Grafana dashboard 自动加载配置
		filepath.Join(outputDir, "monitoring", "grafana", "provisioning", "dashboards", "dashboard.yml"): `apiVersion: 1
providers:
  - name: default
    folder: ''
    type: file
    options:
      path: /etc/grafana/dashboards
`,

		// Grafana dashboard JSON 骨架
		filepath.Join(outputDir, "monitoring", "grafana", "dashboards", name+".json"): fmt.Sprintf(`{
  "title": "%s Dashboard",
  "uid": "%s",
  "panels": [
    {
      "title": "HTTP 请求总数",
      "type": "stat",
      "targets": [
        {
          "expr": "sum(rate(%s_http_request_total[5m]))",
          "legendFormat": "req/s"
        }
      ]
    },
    {
      "title": "HTTP 错误率",
      "type": "timeseries",
      "targets": [
        {
          "expr": "sum(rate(%s_http_request_total{status=~\"5..\"}[5m]))",
          "legendFormat": "5xx/s"
        }
      ]
    },
    {
      "title": "P99 延迟",
      "type": "timeseries",
      "targets": [
        {
          "expr": "histogram_quantile(0.99, rate(%s_http_request_duration_seconds_bucket[5m]))",
          "legendFormat": "P99"
        }
      ]
    },
    {
      "title": "业务错误",
      "type": "timeseries",
      "targets": [
        {
          "expr": "sum by(code) (rate(%s_business_error_total[5m]))",
          "legendFormat": "{{code}}"
        }
      ]
    }
  ],
  "schemaVersion": 38,
  "version": 1
}`, name, name, name, name, name, name),

		filepath.Join(outputDir, "monitoring", "README.md"): readmeContent,
	}

	for path, content := range files {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return fmt.Errorf("gen monitoring file %s: %w", path, err)
		}
	}
	return nil
}

func writeFrontendSkeleton(outputDir, name string) error {
	fe := filepath.Join(outputDir, "frontend")

	files := map[string]string{

		// ── package.json ─────────────────────────────────────────────
		filepath.Join(fe, "package.json"): fmt.Sprintf(`{
  "name": "%s-frontend",
  "private": true,
  "version": "0.0.1",
  "type": "module",
  "scripts": {
    "dev":     "vite",
    "build":   "tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@radix-ui/react-slot":      "^1.1.0",
    "class-variance-authority":  "^0.7.0",
    "clsx":                      "^2.1.1",
    "lucide-react":              "^0.436.0",
    "react":                     "^18.3.1",
    "react-dom":                 "^18.3.1",
    "react-router-dom":          "^6.26.1",
    "tailwind-merge":            "^2.5.2"
  },
  "devDependencies": {
    "@types/react":        "^18.3.4",
    "@types/react-dom":    "^18.3.0",
    "@vitejs/plugin-react":"^4.3.1",
    "autoprefixer":        "^10.4.20",
    "postcss":             "^8.4.45",
    "tailwindcss":         "^3.4.10",
    "typescript":          "^5.5.3",
    "vite":                "^5.4.2"
  }
}
`, name),

		// ── vite.config.ts ────────────────────────────────────────────
		filepath.Join(fe, "vite.config.ts"): `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import path from 'path'

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: { '@': path.resolve(__dirname, './src') },
  },
  server: {
    port: 5173,
    proxy: {
      // 开发时将 /api 请求代理到后端服务，生产环境由 nginx 处理
      '/api': {
        target: 'http://localhost:8080',
        changeOrigin: true,
      },
    },
  },
})
`,

		// ── tsconfig.json ─────────────────────────────────────────────
		filepath.Join(fe, "tsconfig.json"): `{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,
    "baseUrl": ".",
    "paths": { "@/*": ["./src/*"] }
  },
  "include": ["src"]
}
`,

		// ── postcss.config.js ─────────────────────────────────────────
		filepath.Join(fe, "postcss.config.js"): `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`,

		// ── tailwind.config.ts ────────────────────────────────────────
		filepath.Join(fe, "tailwind.config.ts"): `import type { Config } from 'tailwindcss'

export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        border:     'hsl(var(--border))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT:    'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        muted: {
          DEFAULT:    'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        card: {
          DEFAULT:    'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
    },
  },
  plugins: [],
} satisfies Config
`,

		// ── index.html ────────────────────────────────────────────────
		filepath.Join(fe, "index.html"): fmt.Sprintf(`<!doctype html>
<html lang="zh-CN">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>%s</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`, name),

		// ── src/main.tsx ──────────────────────────────────────────────
		filepath.Join(fe, "src", "main.tsx"): `import React from 'react'
import ReactDOM from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import App from './App'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </React.StrictMode>,
)
`,

		// ── src/index.css ─────────────────────────────────────────────
		filepath.Join(fe, "src", "index.css"): `@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    --background:         0 0% 100%;
    --foreground:         224 71.4% 4.1%;
    --card:               0 0% 100%;
    --card-foreground:    224 71.4% 4.1%;
    --border:             220 13% 91%;
    --primary:            220.9 39.3% 11%;
    --primary-foreground: 210 20% 98%;
    --muted:              220 14.3% 95.9%;
    --muted-foreground:   220 8.9% 46.1%;
    --radius:             0.5rem;
  }
  .dark {
    --background:         224 71.4% 4.1%;
    --foreground:         210 20% 98%;
    --card:               224 71.4% 4.1%;
    --card-foreground:    210 20% 98%;
    --border:             215 27.9% 16.9%;
    --primary:            210 20% 98%;
    --primary-foreground: 220.9 39.3% 11%;
    --muted:              215 27.9% 16.9%;
    --muted-foreground:   217.9 10.6% 64.9%;
  }
}

* { border-color: hsl(var(--border)); }
body {
  background-color: hsl(var(--background));
  color: hsl(var(--foreground));
  font-feature-settings: "rlig" 1, "calt" 1;
}
`,

		// ── src/App.tsx ───────────────────────────────────────────────
		filepath.Join(fe, "src", "App.tsx"): `import { Routes, Route, Navigate } from 'react-router-dom'
import { AuthProvider, useAuth } from '@/contexts/AuthContext'
import Layout from '@/components/Layout'
import Login from '@/pages/Login'
import Home from '@/pages/Home'

function PrivateRoute({ children }: { children: React.ReactNode }) {
  const { token } = useAuth()
  return token ? <>{children}</> : <Navigate to="/login" replace />
}

export default function App() {
  return (
    <AuthProvider>
      <Routes>
        <Route path="/login" element={<Login />} />
        <Route
          path="/*"
          element={
            <PrivateRoute>
              <Layout />
            </PrivateRoute>
          }
        >
          <Route index element={<Home />} />
          {/* 在此添加业务页面路由 */}
        </Route>
      </Routes>
    </AuthProvider>
  )
}
`,

		// ── src/api/client.ts ─────────────────────────────────────────
		// 注意：Bearer token 拼接不用模板字符串，避免 Go raw string 反引号冲突
		filepath.Join(fe, "src", "api", "client.ts"): `const BASE = import.meta.env.VITE_API_BASE ?? ''

export class ApiError extends Error {
  constructor(public code: number, message: string) {
    super(message)
    this.name = 'ApiError'
  }
}

async function request<T>(path: string, options: RequestInit = {}): Promise<T> {
  const token = localStorage.getItem('access_token')
  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
    ...(options.headers as Record<string, string>),
  }
  if (token) headers['Authorization'] = 'Bearer ' + token

  const res  = await fetch(BASE + path, { ...options, headers })
  const json = await res.json()

  if (json.code !== 0) {
    throw new ApiError(json.code, json.message ?? '请求失败')
  }
  return json.data as T
}

export const api = {
  get:    <T>(path: string)                => request<T>(path, { method: 'GET' }),
  post:   <T>(path: string, body: unknown) => request<T>(path, { method: 'POST',   body: JSON.stringify(body) }),
  put:    <T>(path: string, body: unknown) => request<T>(path, { method: 'PUT',    body: JSON.stringify(body) }),
  delete: <T>(path: string)               => request<T>(path, { method: 'DELETE' }),
}
`,

		// ── src/contexts/AuthContext.tsx ──────────────────────────────
		filepath.Join(fe, "src", "contexts", "AuthContext.tsx"): `import { createContext, useContext, useState, useCallback } from 'react'
import { api } from '@/api/client'

interface AuthState {
  token:    string | null
  username: string | null
  userID:   number | null
}

interface AuthContextValue extends AuthState {
  login:  (username: string, password: string) => Promise<void>
  logout: () => Promise<void>
}

const AuthContext = createContext<AuthContextValue | null>(null)

export function AuthProvider({ children }: { children: React.ReactNode }) {
  const [state, setState] = useState<AuthState>({
    token:    localStorage.getItem('access_token'),
    username: localStorage.getItem('username'),
    userID:   Number(localStorage.getItem('user_id')) || null,
  })

  const login = useCallback(async (username: string, password: string) => {
    const data = await api.post<{
      access_token:  string
      refresh_token: string
      username:      string
      user_id:       number
    }>('/api/v1/login', { username, password })

    localStorage.setItem('access_token',  data.access_token)
    localStorage.setItem('refresh_token', data.refresh_token)
    localStorage.setItem('username',      data.username)
    localStorage.setItem('user_id',       String(data.user_id))

    setState({ token: data.access_token, username: data.username, userID: data.user_id })
  }, [])

  const logout = useCallback(async () => {
    const rt = localStorage.getItem('refresh_token')
    if (rt) {
      await api.post('/api/v1/logout', { refresh_token: rt }).catch(() => {})
    }
    localStorage.clear()
    setState({ token: null, username: null, userID: null })
  }, [])

  return (
    <AuthContext.Provider value={{ ...state, login, logout }}>
      {children}
    </AuthContext.Provider>
  )
}

export function useAuth() {
  const ctx = useContext(AuthContext)
  if (!ctx) throw new Error('useAuth must be inside AuthProvider')
  return ctx
}
`,

		// ── src/components/Layout.tsx ─────────────────────────────────
		// nav 为空数组，业务层自行追加
		filepath.Join(fe, "src", "components", "Layout.tsx"): fmt.Sprintf(`import { Outlet, NavLink, useNavigate } from 'react-router-dom'
import { useAuth } from '@/contexts/AuthContext'
import { LogOut } from 'lucide-react'

// 在此追加业务导航项，例如：
// import { LayoutDashboard } from 'lucide-react'
// { to: '/dashboard', label: '总览', icon: LayoutDashboard }
const nav: { to: string; label: string; icon: React.ElementType }[] = []

export default function Layout() {
  const { username, logout } = useAuth()
  const navigate = useNavigate()

  const handleLogout = async () => {
    await logout()
    navigate('/login')
  }

  return (
    <div className="flex h-screen bg-background">
      <aside className="w-56 border-r flex flex-col py-6 px-3 gap-1">
        <div className="px-3 mb-6">
          <h1 className="text-lg font-semibold tracking-tight">%s</h1>
          <p className="text-xs text-muted-foreground mt-0.5">{username}</p>
        </div>

        {nav.map(({ to, label, icon: Icon }) => (
          <NavLink
            key={to}
            to={to}
            end={to === '/'}
            className={({ isActive }) =>
              [
                'flex items-center gap-3 rounded-md px-3 py-2 text-sm transition-colors',
                isActive
                  ? 'bg-primary text-primary-foreground font-medium'
                  : 'text-muted-foreground hover:bg-muted hover:text-foreground',
              ].join(' ')
            }
          >
            <Icon size={16} />
            {label}
          </NavLink>
        ))}

        <div className="mt-auto">
          <button
            onClick={handleLogout}
            className="flex w-full items-center gap-3 rounded-md px-3 py-2 text-sm text-muted-foreground hover:bg-muted hover:text-foreground transition-colors"
          >
            <LogOut size={16} />
            退出登录
          </button>
        </div>
      </aside>

      <main className="flex-1 overflow-auto">
        <div className="mx-auto max-w-4xl px-8 py-8">
          <Outlet />
        </div>
      </main>
    </div>
  )
}
`, name),

		// ── src/pages/Login.tsx ───────────────────────────────────────
		filepath.Join(fe, "src", "pages", "Login.tsx"): fmt.Sprintf(`import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '@/contexts/AuthContext'
import { ApiError } from '@/api/client'

export default function Login() {
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [error,    setError]    = useState('')
  const [loading,  setLoading]  = useState(false)
  const { login } = useAuth()
  const navigate  = useNavigate()

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setError('')
    setLoading(true)
    try {
      await login(username, password)
      navigate('/')
    } catch (err) {
      setError(err instanceof ApiError ? err.message : '登录失败，请重试')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="flex min-h-screen items-center justify-center bg-muted/40">
      <div className="w-full max-w-sm rounded-xl border bg-card p-8 shadow-sm">
        <h1 className="text-2xl font-semibold tracking-tight mb-1">%s</h1>
        <p className="text-sm text-muted-foreground mb-6">登录以继续</p>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="space-y-1.5">
            <label className="text-sm font-medium">用户名</label>
            <input
              type="text"
              value={username}
              onChange={e => setUsername(e.target.value)}
              required
              autoFocus
              className="w-full rounded-md border bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-primary/30"
            />
          </div>
          <div className="space-y-1.5">
            <label className="text-sm font-medium">密码</label>
            <input
              type="password"
              value={password}
              onChange={e => setPassword(e.target.value)}
              required
              className="w-full rounded-md border bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-primary/30"
            />
          </div>
          {error && <p className="text-sm text-red-500">{error}</p>}
          <button
            type="submit"
            disabled={loading}
            className="w-full rounded-md bg-primary py-2 text-sm font-medium text-primary-foreground hover:opacity-90 disabled:opacity-50 transition-opacity"
          >
            {loading ? '登录中…' : '登录'}
          </button>
        </form>
      </div>
    </div>
  )
}
`, name),

		// ── src/pages/Home.tsx ────────────────────────────────────────
		// 纯占位页，无任何业务逻辑
		filepath.Join(fe, "src", "pages", "Home.tsx"): fmt.Sprintf(`import { useAuth } from '@/contexts/AuthContext'

export default function Home() {
  const { username } = useAuth()
  return (
    <div className="flex flex-col items-center justify-center h-full gap-3 text-center">
      <h2 className="text-2xl font-semibold">欢迎使用 %s</h2>
      <p className="text-muted-foreground text-sm">你好，{username}。请从左侧导航开始。</p>
    </div>
  )
}
`, name),

		// ── Dockerfile ────────────────────────────────────────────────
		filepath.Join(fe, "Dockerfile"): `FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
`,

		// ── nginx.conf ────────────────────────────────────────────────
		filepath.Join(fe, "nginx.conf"): `server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /api/ {
    proxy_pass       http://backend:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
`,

		// ── .gitignore ────────────────────────────────────────────────
		filepath.Join(fe, ".gitignore"): `node_modules/
dist/
.env.local
.env.*.local
`,
	}

	for path, content := range files {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return fmt.Errorf("gen frontend file %s: %w", path, err)
		}
	}
	return nil
}
